src/modules/base/avatar/avatar.js
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/carousel/__docs__/carousel.stories.js
src/modules/base/carousel/carousel.js
src/modules/base/dateTimePicker/dateTimePicker.js
src/modules/base/inputToggle/inputToggle.js
src/modules/base/primitiveWizardNavigation/primitiveWizardNavigation.js
src/modules/base/relationshipGraph/relationshipGraph.js
src/modules/base/summaryDetail/summaryDetail.js
src/modules/base/wizard/wizard.js

Components checked:
- Input toggle
- Carousel
- Avatar
- Date Time Picker
- Wizard / Wizard Step / Primitive Wizard Navigation
- Relationship Graph
- Summary Detail
- Avatar group

[fix] (ABC-151): Normalize values received by setters

---

src/modules/base/carousel/__docs__/carousel.stories.js
src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.css
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js

ABC-185- Switched heading to title
ABC-186- Added secondary button fields to items object in carousel.js
ABC-187- updated confluence docs for carousel items with secondaryButton

Feat abc 184 carousel new features

---

src/modules/base/dualListbox/__docs__/dualListbox.stories.js
src/modules/base/dualListbox/__examples__/dualListbox.js
src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.css
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js

- Added attribute width to dual listbox
- Created test and stories for new attribute

Feature (ABC-197) add attribute width to dual listbox

---

src/modules/base/dualListbox/__docs__/dualListbox.stories.js
src/modules/base/dualListbox/__examples__/dualListbox.js
src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.css
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js

- Fixed issue with size
- Changed size attribute name to max-visible-options
- Changed width attribute name to size

Bugfix ABC-195 issue with size

---

src/modules/base/primitiveProgressBarReferenceLine/primitiveProgressBarReferenceLine.js
src/modules/base/progressBar/progressBar.js

- Added a large margin-bottom when there is reference lines

[fix] (ABC-203): Fixed issue with referenceLines and position absolute

---

src/modules/base/buttonDialog/__tests__/buttonDialog.test.js
src/modules/base/buttonDialog/buttonDialog.js
src/modules/base/buttonIconDialog/__tests__/buttonIconDialog.test.js
src/modules/base/buttonIconDialog/buttonIconDialog.js

- Added show and hide methods for button dialog and button icon dialog
- Added tests for both

Feature abc 206 show and hide method to button dialog and button icon dialog

---

src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js

- Added method First & Last
- Changed name to have methods start, pause, next and previous
- Added tests for each methods
- Added tests for isInfinite

Feature ABC-226 add methods to carousel

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

List actions : 
- 1 action no label : button-icon
- 1 action label : button
- multi actions : button menu

(feat) (abc 243) list component actions display

---

src/modules/base/filterMenuGroup/filterMenuGroup.js
src/modules/base/inputCounter/__tests__/inputCounter.test.js
src/modules/base/inputCounter/inputCounter.js
src/modules/base/list/list.html
src/modules/base/tooltipLibrary/tooltipLibrary.js

- Remove console.log in filterMenuGroup
- Set default value to null in inputCounter
- Set default ALIGN to empty object in tooltipLibrary
- Add a template condition in list

[test] (ABC-296): Fix tests errors

---

src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/__examples__/sortableList/sortableList.html
src/modules/base/list/__examples__/sortableList/sortableList.js
src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js

- Stop using label as a key.
- Fix actionclick undefined item.
- Fix action position.
- Make sure itemclick event is sent every time, not every other time.
- Do not send reorder event when the order didn't change.
- Fix truncate.

[fix] (ABC-334): Fix issues with list

---

src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.js

Feature ABC 315 change method start to play in carousel

---

src/modules/base/expandableSection/__tests__/expandableSection.test.js
src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.html
src/modules/base/expandableSection/expandableSection.js

--avonni-expandable-section-header-spacing-block-start
--avonni-expandable-section-header-spacing-block-end

[feat] (ABC-339): Add styling hooks to expandable section

---

src/modules/base/mediaObject/mediaObject.html
src/modules/base/mediaObject/mediaObject.js

Needed to fix avatar image not showing up if source is added after connectedCallback.

[fix] (ABC-346): Always display figure slots in mediaObject

---

src/modules/base/combobox/__docs__/combobox.stories.js
src/modules/base/combobox/__examples__/combobox.js
src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

- Added attribute messageWhenBadInput
- Implemented constraint for it
- Created tests for attribute

Feat ABC-355 message when bad input for combobox

---

src/modules/base/dualListbox/__docs__/data.js
src/modules/base/dualListbox/__docs__/dualListbox.jsdoc.js
src/modules/base/dualListbox/__docs__/dualListbox.stories.js
src/modules/base/dualListbox/__examples__/baseResponsive/baseResponsive.html
src/modules/base/dualListbox/__examples__/baseResponsive/baseResponsive.js
src/modules/base/dualListbox/__examples__/baseWithAvatar/baseWithAvatar.js
src/modules/base/dualListbox/__examples__/baseWithAvatarDescriptionVisibleOptions6/baseWithAvatarDescriptionVisibleOptions6.js
src/modules/base/dualListbox/__examples__/baseWithAvatarLabelHidden/baseWithAvatarLabelHidden.js
src/modules/base/dualListbox/__examples__/baseWithAvatarReorderingDisabled/baseWithAvatarReorderingDisabled.js
src/modules/base/dualListbox/__examples__/baseWithAvatarVisibleOptions10/baseWithAvatarVisibleOptions10.js
src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js

- Change option's avatar markup
- Normalized Button Icon Name
- Fixed issue with allowSearch
- added missing documentation
- added responsive option to size

Fix ABC-394 Fixed dual-listbox issues

---

src/modules/base/calendar/__docs__/calendar.jsdoc.js
src/modules/base/calendar/__docs__/calendar.stories.js
src/modules/base/calendar/__examples__/base/base.html
src/modules/base/calendar/calendar.css
src/modules/base/calendar/calendar.js
src/modules/base/inputDateRange/inputDateRange.html
src/modules/base/inputDateRange/inputDateRange.js

- Manage focus between each input for input-date-range
- Fixed issue with date format
- Change UI for calendar when in interval selection mode
- Changed time formatting depending on timestyle when on readOnly

Fix ABC 379 Manage Calendar and Input-date-range

---

src/modules/base/progressCircle/__tests__/progressCircle.test.js
src/modules/base/progressCircle/progressCircle.html
src/modules/base/progressCircle/progressCircle.js

- Fixed issue with title and label
- Changed tests

[fix] (ABC-411): Fixed issue with title and label

---

src/modules/base/qrcode/__tests__/qrcode.test.js
src/modules/base/qrcode/qrcode.js

- Normalized attributes color and background
- Added tests for both

[fix] (ABC-412): Normalized attributes color and background

---

src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.js

- Fixed issue with change event of calendar
- Fixed issue when no disabled dates

Fix ABC-416 Issue with calendar in date-time-picker

---

src/modules/base/progressBar/progressBarVertical.css
src/modules/base/range/__docs__/range.jsdoc.js
src/modules/base/range/__docs__/range.stories.js
src/modules/base/range/__examples__/verticalLarge/verticalLarge.html
src/modules/base/range/__examples__/verticalSmall/verticalSmall.html
src/modules/base/range/__tests__/range.test.js
src/modules/base/range/range.css
src/modules/base/range/range.html
src/modules/base/range/range.js

- Added full option to size attribute
- Added size attribute to vertical option
- Renamed classes to follow CSS naming convention
- Changed tests
- Added stories and documentation for it

Feat ABC-418 Add size to vertical range

---

src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/alert/__tests__/alert.test.js
src/modules/base/alert/alert.css
src/modules/base/alert/alert.html
src/modules/base/alert/alert.js

- Changed theme classes 
- Added styling hooks and documentation
- Changed tests

Feat ABC-432 add styling hooks to alert

---

src/modules/base/image/__docs__/image.jsdoc.js
src/modules/base/image/image.css

- Changed border's styling hooks

Feat ABC-431 Changed image styling hooks

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/dualListbox/__docs__/data.js
src/modules/base/dualListbox/__docs__/dualListbox.jsdoc.js
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js
src/modules/base/list/__docs__/list.jsdoc.js
src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html

- Added presence to avatar in dual listbox and list
- Icon instead of button icon in activity timeline
- fix issue with drag in dual listbox
- avatar as object in list
- icons a string in list

Fix ABC-447 Change in dual-listbox, list and activity-timeline

---

package.json
scripts/createNewComponent.js

`npm run newComponent nameOfTheComponent`

[feat] (ABC-455): Add a script to create a new component

---

src/modules/base/dynamicMenu/__docs__/data.js
src/modules/base/dynamicMenu/__docs__/dynamicMenu.stories.js
src/modules/base/dynamicMenu/__examples__/dynamicMenu.js
src/modules/base/dynamicMenu/__examples__/dynamicMenuInGroup.js
src/modules/base/dynamicMenu/__examples__/listView.js
src/modules/base/dynamicMenu/__tests__/dynamicMenu.test.js
src/modules/base/dynamicMenu/dynamicMenu.html
src/modules/base/dynamicMenu/dynamicMenu.js
src/modules/base/storybookWrappers/dynamicMenu/dynamicMenu.html
src/modules/base/storybookWrappers/dynamicMenu/dynamicMenu.js
src/modules/base/storybookWrappers/dynamicMenu/dynamicMenuInGroup.html
src/modules/base/storybookWrappers/dynamicMenu/dynamicMenuInGroup.js
src/modules/base/storybookWrappers/dynamicMenu/listView.html
src/modules/base/storybookWrappers/dynamicMenu/listView.js

- Added menu-width
- Change scrolling in menu 
- Added item in detail for actionclick event

Feat ABC-469 dropdown-menu

---

src/modules/base/carousel/carousel.css
src/modules/base/carousel/carousel.html
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js

- Added min width to lightning-layout-item containing carousel stage

Fix ABC-481 Fixed responsive issue with carousel

---

src/modules/base/dualListbox/dualListbox.js
src/modules/base/heroBanner/heroBanner.js
src/modules/base/primitiveReferenceLine/__tests__/primitiveReferenceLine.test.js
src/modules/base/primitiveReferenceLine/primitiveReferenceLine.js
src/modules/base/progressBar/progressBar.js
src/modules/base/progressCircle/progressCircle.js
src/modules/base/qrcode/qrcode.js
src/modules/base/rating/rating.js
src/modules/base/timer/timer.js

- Dual-Listbox : max-visible-options, max, min
- Hero-banner: height, max-width, content-width
- Primitive-reference-line: value
- Progress-bar: value
- Progress-circle: value
- QR-code: border-width, padding
- Rating: min, max
- Timer: value

Fix ABC-473 Accepting string and integer for different attributes

---

lwc.config.json
src/modules/base/treeGrid/__docs__/data.js
src/modules/base/treeGrid/__docs__/treeGrid.stories.js
src/modules/base/treeGrid/__examples__/base/base.html
src/modules/base/treeGrid/__examples__/base/base.js
src/modules/base/treeGrid/__examples__/expanded/expanded.html
src/modules/base/treeGrid/__examples__/expanded/expanded.js
src/modules/base/treeGrid/__examples__/treeGrid.js
src/modules/base/treeGrid/normalizer.js
src/modules/base/treeGrid/treeGrid.html
src/modules/base/treeGrid/treeGrid.js
src/modules/base/treeGrid/treeGrid.js-meta.xml

- Created tree-grid component
- Added documentation (jsDoc)
- Added examples (jsDoc)

Feat ABC-482 tree grid component

---

src/modules/base/dualListbox/dualListbox.js

Fix search in dual listbox so that you can lowercase and uppercase both return results. 
Fix rangeOverflow error message when max is not set. 
Default max now set to undefined instead of empty string.

Feature abc 471 dual list box searching case

---

src/modules/base/progressCircle/__docs__/progressCircle.stories.js
src/modules/base/progressCircle/__examples__/drainLoadingWithThicknessXSmall/drainLoadingWithThicknessXSmall.html
src/modules/base/progressCircle/__examples__/drainLoadingWithThicknessXSmall/drainLoadingWithThicknessXSmall.js
src/modules/base/progressCircle/__examples__/progressCircle.js
src/modules/base/progressCircle/__tests__/progressCircle.test.js
src/modules/base/progressCircle/progressCircle.css
src/modules/base/progressCircle/progressCircle.html
src/modules/base/progressCircle/progressCircle.js

Added a loading animation that spins while isLoading is true.

Feature abc 475 add is loading to progress circle

---

src/modules/base/dynamicMenu/dynamicMenu.css
src/modules/base/dynamicMenu/dynamicMenu.html
src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/visualPicker.css

- Dynamic menu : minimum height on item
- Visual picker : Fixed issue with centered title

Fix ABC-507 Dynamic menu and Visual picker

---

src/modules/base/list/__docs__/list.jsdoc.js
src/modules/base/list/list.css
src/modules/base/list/list.js

- --avonni-list-item-color-background-hover-sortable ✅
- --avonni-list-item-color-background-sortable ✅
- --avonni-list-item-spacing-block-between ✅
- --avonni-list-item-spacing-block-start ✅
- --avonni-list-item-spacing-block-end ✅
- --avonni-list-item-spacing-inline-start ✅
- --avonni-list-item-spacing-inline-end ✅
- --avonni-list-item-cursor ✅
- --avonni-list-item-cursor-sortable ✅

[feat] (ABC-489): Add and improve list styling hooks

---

src/modules/base/dialog/__tests__/dialog.test.js
src/modules/base/dialog/dialog.html
src/modules/base/dialog/dialog.js

**Dialog**
- Add `outsideclick` event

[feat] (ABC-511): Add outsideclick event to dialog

---

src/modules/base/pageHeader/__docs__/pageHeader.stories.js
src/modules/base/pageHeader/__examples__/base/base.html
src/modules/base/pageHeader/__examples__/pageHeader.js
src/modules/base/pageHeader/__tests__/pageHeader.test.js
src/modules/base/pageHeader/pageHeader.html
src/modules/base/pageHeader/pageHeader.js
src/modules/base/pageHeader/pageHeaderVertical.html
src/modules/base/storybookWrappers/pageHeader/pageHeader.html
src/modules/base/storybookWrappers/pageHeader/pageHeader.js

Added storybook controls and implemented isJoined to add slds-page-header_joined. Works on vertical too.
Removed slds classes from title slot.

Feature abc 479 add is joined to page header

---

src/modules/base/colorPalette/list.html

**Color Palette**
- Show the color label on hover, in the list variant.

[fix] (ABC-519): Change the fixed title for a dynamic one

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__examples__/inputChoiceSet.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

Add boolean `stretch` to add `.avonni-input-choice-set__stretch` to button groups.

[feat][wip] (ABC-514): Add responsive stretch class

---

package-lock.json
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Fix dropdown not overlapping content.
- Fix systematic bad input error when options are nested more than one level.

[fix] (ABC-520): Fix combobox dropdown positioning and wrong error

---

src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.js

**Tree**
- Added `blur()` and `focus()` methods.

[feat] (ABC-525): Add focus and blur methods to tree

---

src/modules/base/calendar/calendar.js
src/modules/base/inputDateRange/inputDateRange.js

**Fixes**
- Included time zone in calendar's change event value.
**Fixes**
- Fixed wrong date selection depending on the time zone.

[fix] (ABC-535): Include time zone in calendar change event value

---

src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.css
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.js
src/modules/base/visualPicker/__docs__/data.js
src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/__docs__/visualPicker.stories.js
src/modules/base/visualPicker/__examples__/baseWithIcons/baseWithIcons.html
src/modules/base/visualPicker/__examples__/baseWithIcons/baseWithIcons.js
src/modules/base/visualPicker/__examples__/templates/templates.html
src/modules/base/visualPicker/__examples__/templates/templates.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Changed way of displaying image
- Added new stories
- Updated documentation

Feat ABC-523 Refactor visual picker

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__examples__/inputChoiceSet.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added `is-loading` attribute.

[feat] (ABC-543): Add is-loading to input choice set

---

src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/colorPalette/colorPalette.js
src/modules/base/colorPicker/colorPicker.js
src/modules/base/inputChoiceSet/inputChoiceSet.js
src/modules/base/outputData/outputData.js
src/modules/base/path/path.js
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/relationshipGraph/relationshipGraph.js
src/modules/base/tree/tree.js

**Activity Timeline, Color Palette, Color Picker, Input Choice Set, Output Data, Path, Relationship Graph and Tree**
- Fixed the update of specific properties after the component insertion into the DOM, when used on the Salesforce platform.

[fix] (ABC-562): Replace all default this.isConnected by a property

---

src/modules/base/activityTimeline/__docs__/data.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/expandableSection/__docs__/expandableSection.jsdoc.js
src/modules/base/expandableSection/__docs__/expandableSection.stories.js
src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.html
src/modules/base/expandableSection/expandableSection.js
src/modules/base/utilsPrivate/normalize.js

- Added styling hooks:
- `--avonni-expandable-section-base-header-text-color-focus`
- `--avonni-expandable-section-base-header-text-color-hover`
- `--avonni-expandable-section-base-header-text-decoration-focus`
- `--avonni-expandable-section-shaded-header-text-color-focus`
- `--avonni-expandable-section-shaded-header-text-color-hover`
- `--avonni-expandable-section-shaded-header-text-decoration-focus`
- `--avonni-expandable-section-base-header-icon-color-foreground-default-hover`
- `--avonni-expandable-section-base-header-icon-color-foreground-default-focus`
- `--avonni-expandable-section-shaded-header-icon-color-foreground-default-hover`
- `--avonni-expandable-section-shaded-header-icon-color-foreground-default-focus`
- Made the toggle icon …

[feat] (ABC-561): Allow for same style as accordion in expandable section

---

src/modules/base/inputRichText/__docs__/inputRichText.stories.js
src/modules/base/inputRichText/inputRichText.html
src/modules/base/inputRichText/inputRichText.js

**Input Rich Text**
- Fixed variant update after the input value has been changed by the user.

[fix] (ABC-560): Fix variant change in input richtext

---

src/modules/base/datatable/__docs__/data.js
src/modules/base/datatable/__examples__/dataTypesFromDtoO/dataTypesFromDtoO.js
src/modules/base/image/__docs__/image.stories.js
src/modules/base/image/__examples__/base/base.html
src/modules/base/image/__examples__/baseLarge/baseLarge.html
src/modules/base/image/__examples__/baseSmall/baseSmall.html
src/modules/base/image/__examples__/baseWithLazyLoading/baseWithLazyLoading.js
src/modules/base/image/__examples__/center/center.html
src/modules/base/image/__examples__/cropImageStaticThumbnailMobile/cropImageStaticThumbnailMobile.html
src/modules/base/image/__examples__/right/right.html
src/modules/base/image/__examples__/thumbnail/thumbnail.html
src/modules/base/image/__tests__/image.test.js
src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/__examples__/images/images.js
src/modules/base/list/__examples__/sortableWithImagesAndAvatars/sortableWithImagesAndAvatars.js
src/modules/base/list/__tests__/data.js
src/modules/base/list/list.html

- Replaced found dead image link in storybook and examples

[fix] (abc-526): Support rich text in list item

---

src/modules/base/carousel/__docs__/carousel.jsdoc.js
src/modules/base/carousel/__docs__/data.js
src/modules/base/carousel/__examples__/base/base.js
src/modules/base/carousel/__examples__/baseWithFiveItemsPerPanel/baseWithFiveItemsPerPanel.js
src/modules/base/carousel/__examples__/baseWithNoProgressIndicator/baseWithNoProgressIndicator.js
src/modules/base/carousel/__examples__/baseWithThreeItemsPerPanelAndVariantShaded/baseWithThreeItemsPerPanelAndVariantShaded.js
src/modules/base/carousel/__examples__/baseWithTwoItemsPerPanel/baseWithTwoItemsPerPanel.js
src/modules/base/carousel/__examples__/withoutPanelNavigation/withoutPanelNavigation.js
src/modules/base/carousel/__examples__/withoutPanelNavigationWithFiveItemsPerPanel/withoutPanelNavigationWithFiveItemsPerPanel.js
src/modules/base/carousel/__examples__/withoutPanelNavigationWithThreeItemsPerPanel/withoutPanelNavigationWithThreeItemsPerPanel.js
src/modules/base/carousel/__examples__/withoutPanelNavigationWithTwoItemsPerPanel/withoutPanelNavigationWithTwoItemsPerPanel.js
src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js
src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js

**Carousel**
- Renamed the items `id` to `name`.

[feat] (ABC-555): Rename id to name in carousel items

---

src/modules/base/filterMenu/__docs__/filterMenu.stories.js
src/modules/base/filterMenu/__examples__/filterMenu.js
src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.html
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenu/filterMenuVertical.html

**Filter-menu**
- Added name attribute
- Added tests for name attribute

Feat ABC-614 Filter menu -- add name attribute

---

src/modules/base/iconPicker/__tests__/iconPicker.test.js
src/modules/base/iconPicker/iconPicker.css
src/modules/base/iconPicker/iconPicker.html
src/modules/base/iconPicker/iconPicker.js

Icon Picker
- Added focus() public method

[Feature] (ABC-547) Add focus method icon picker

---

src/modules/base/pageHeader/pageHeader.html

**Page Header**
- Actions now appear on small and large mobile devices for base, object home and record home variants

[fix] (ABC-586): Actions are present in small and large mobile devices

---

src/modules/base/colorGradient/colorGradient.css
src/modules/base/colorGradient/colorGradient.html
src/modules/base/colorGradient/colorGradient.js

**Color Gradient**
- The color picker indicator is now draggable
- The hue slider was set to the left when the color selected was in the corner of the gradient

[fix] (ABC-606) Color Gadrient drag and event propagation

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__examples__/activityTimeline.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.html
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js

ActivityTimeline
- Added iconSize and itemIconSize to customize size of icons

[feat](ABC-532) : ActivityTimeline : Add controls to change size of icons

---

src/modules/base/rating/__tests__/rating.test.js
src/modules/base/rating/rating.css
src/modules/base/rating/rating.js

**Rating**
- Now displays the rating with the lower scores on top

[fix] (ABC-589) Rating value wrapping order

---

src/modules/base/dateTimePicker/dateTimePicker.js

No changes compared to the previous release.

[fix] (ABC-616): Fix ABC-556 overwritten by ABC-476

---

src/modules/base/storybookWrappers/timer/timerButtons.html
src/modules/base/storybookWrappers/timer/timerButtons.js
src/modules/base/timer/__docs__/timer.stories.js
src/modules/base/timer/__examples__/base/base.html
src/modules/base/timer/__examples__/base/base.js
src/modules/base/timer/__examples__/brandIcon/brandIcon.html
src/modules/base/timer/__examples__/brandIcon/brandIcon.js
src/modules/base/timer/__examples__/chronoCountdown/chronoCountdown.html
src/modules/base/timer/__examples__/chronoCountdown/chronoCountdown.js
src/modules/base/timer/__examples__/destructiveCountdown/destructiveCountdown.html
src/modules/base/timer/__examples__/successSeconds/successSeconds.html
src/modules/base/timer/__examples__/timer.js
src/modules/base/timer/__examples__/timerButtons.js
src/modules/base/timer/__tests__/timer.test.js
src/modules/base/timer/timer.js

**Timer**
- Timer works with milliseconds.
- 2 new display formats: "mm:ss.ms" & "ss.ms"
**Timer**
- Countdown type now works.
- Pause now works.
- Reset method now works.
- Repeat attribute now works.
- Refactored formatting to be flexible. Can now easily add more display formats.
**Times**
- Value attribute is now given in milliseconds instead of seconds.
- Duration caps at 24 hours.

[fix] (ABC- 593) Timer - broken count-down and much more

---

src/modules/base/range/__docs__/range.stories.js
src/modules/base/range/__examples__/minMaxStep/minMaxStep.html
src/modules/base/range/__tests__/range.test.js
src/modules/base/range/range.css
src/modules/base/range/range.html
src/modules/base/range/range.js

Range
- Range is now composed of 2 inputs overlayed
Range
- New structure removes the "wobble" effect on range change
- If both inputs have the same value, input thumbs overlap

Bugfix (ABC-621): reworked the range component

---

jest-mock/components/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Added `resetLevel()` method.

[feat] (ABC-657): Add resetLevel() to combobox

---

src/modules/base/alert/__docs__/alert.stories.js
src/modules/base/alert/__examples__/dismissibleWithCloseAction/dismissibleWithCloseAction.html
src/modules/base/alert/__examples__/dismissibleWithCloseAction/dismissibleWithCloseAction.js
src/modules/base/alert/__tests__/alert.test.js
src/modules/base/alert/alert.html
src/modules/base/alert/alert.js

**Alert**
- Fixed `is-dismissible` being `true` by default.

[fix] (ABC-568): Fix is-dismissible always true in alert

---

src/modules/base/primitiveTreeItem/primitiveTreeItem.css
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/utilsPrivate/normalize.js

**Tree**
- Fixed the action menu of nested items being overlayed by the next items.

[fix] (ABC-659): Fix action menu of tree nested items

---

package-lock.json

Update package-lock.json version number.

[version] (ABCW-54): build and deploy storybook v1.3.1

---

lwc.config.json
src/modules/base/chip/chip.css
src/modules/base/chip/chip.html
src/modules/base/chipContainer/__docs__/chipContainer.jsdoc.js
src/modules/base/chipContainer/__docs__/chipContainer.stories.js
src/modules/base/chipContainer/__docs__/data.js
src/modules/base/chipContainer/__examples__/base/base.html
src/modules/base/chipContainer/__examples__/base/base.js
src/modules/base/chipContainer/__examples__/chipContainer.js
src/modules/base/chipContainer/__examples__/collapsed/collapsed.html
src/modules/base/chipContainer/__examples__/collapsed/collapsed.js
src/modules/base/chipContainer/__examples__/maxWidthChipContainer.js
src/modules/base/chipContainer/__examples__/noMedia/noMedia.html
src/modules/base/chipContainer/__examples__/noMedia/noMedia.js
src/modules/base/chipContainer/__tests__/chipContainer.test.js
src/modules/base/chipContainer/chipContainer.css
src/modules/base/chipContainer/chipContainer.html
src/modules/base/chipContainer/chipContainer.js
src/modules/base/chipContainer/chipContainer.js-meta.xml
src/modules/base/primitiveChip/__tests__/primitiveChip.test.js
src/modules/base/primitiveChip/primitiveChip.css
src/modules/base/primitiveChip/primitiveChip.html
src/modules/base/primitiveChip/primitiveChip.js
src/modules/base/primitiveChip/primitiveChip.js-meta.xml
src/modules/base/storybookWrappers/chipContainer/maxWidthChipContainer.html
src/modules/base/storybookWrappers/chipContainer/maxWidthChipContainer.js

Chip Container
- Display a list of chips from list of items (see doc)
- Possibility of displaying either an avatar or icon as media (left or right)
- Possibility of changing media size
- Collapsible and expandable
*see: https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/2147581953/Chip+Container

[Feature] (ABC-599): Created new component - chip container

---

lwc.config.json
scripts/createNewComponent.js
src/modules/base/metrics/__docs__/metrics.jsdoc.js
src/modules/base/metrics/__docs__/metrics.stories.js
src/modules/base/metrics/__examples__/base/base.html
src/modules/base/metrics/__examples__/base/base.js
src/modules/base/metrics/__examples__/labelAndDescription/labelAndDescription.html
src/modules/base/metrics/__examples__/labelAndDescription/labelAndDescription.js
src/modules/base/metrics/__examples__/metrics.js
src/modules/base/metrics/__examples__/prefixAndSuffix/prefixAndSuffix.html
src/modules/base/metrics/__examples__/prefixAndSuffix/prefixAndSuffix.js
src/modules/base/metrics/__examples__/secondaryTrendUp/secondaryTrendUp.html
src/modules/base/metrics/__examples__/secondaryTrendUp/secondaryTrendUp.js
src/modules/base/metrics/__examples__/trendDown/trendDown.html
src/modules/base/metrics/__examples__/trendDown/trendDown.js
src/modules/base/metrics/__tests__/metrics.test.js
src/modules/base/metrics/metrics.css
src/modules/base/metrics/metrics.html
src/modules/base/metrics/metrics.js
src/modules/base/metrics/metrics.js-meta.xml
src/modules/base/primitiveMetric/__tests__/primitiveMetric.test.js
src/modules/base/primitiveMetric/primitiveMetric.css
src/modules/base/primitiveMetric/primitiveMetric.html
src/modules/base/primitiveMetric/primitiveMetric.js
src/modules/base/primitiveMetric/primitiveMetric.js-meta.xml

**Metrics**
- Created the metrics component.

[feat] (ABC-642): Create the metrics component

---

src/modules/base/primitiveProgressStep/__tests__/primitiveProgressStep.test.js
src/modules/base/primitiveProgressStep/primitiveProgressStep.html
src/modules/base/primitiveProgressStep/primitiveProgressStep.js
src/modules/base/progressIndicator/__tests__/progressIndicator.test.js
src/modules/base/progressIndicator/progressIndicator.js

**Progress Indicator**
- Added value as detail to each events
- Added stylinghooks to top label and description in progress step

[Doc] (ABC-692): Progress indicator - Add value to events, added stylinghooks to top label and description

---

src/modules/base/list/__docs__/list.jsdoc.js
src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/__examples__/actions/actions.js
src/modules/base/list/__tests__/data.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

Add name to list item, to be returned when item is clicked.

[feature](abc-565): Add name to list item

---

lwc.config.json
src/modules/base/list/__tests__/list.test.js
src/modules/base/metric/__docs__/metric.jsdoc.js
src/modules/base/metric/__docs__/metric.stories.js
src/modules/base/metric/__examples__/base/base.html
src/modules/base/metric/__examples__/base/base.js
src/modules/base/metric/__examples__/labelAndDescription/labelAndDescription.html
src/modules/base/metric/__examples__/labelAndDescription/labelAndDescription.js
src/modules/base/metric/__examples__/metric.js
src/modules/base/metric/__examples__/prefixAndSuffix/prefixAndSuffix.html
src/modules/base/metric/__examples__/prefixAndSuffix/prefixAndSuffix.js
src/modules/base/metric/__examples__/secondaryTrendUp/secondaryTrendUp.html
src/modules/base/metric/__examples__/secondaryTrendUp/secondaryTrendUp.js
src/modules/base/metric/__examples__/trendDown/trendDown.html
src/modules/base/metric/__examples__/trendDown/trendDown.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.css
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js
src/modules/base/metric/metric.js-meta.xml
src/modules/base/metrics/__examples__/base/base.html
src/modules/base/metrics/__examples__/base/base.js
src/modules/base/metrics/__examples__/prefixAndSuffix/prefixAndSuffix.js
src/modules/base/metrics/__examples__/trendDown/trendDown.js
src/modules/base/primitiveMetric/primitiveMetric.css
src/modules/base/primitiveMetric/primitiveMetric.html

[feat] (ABC-697): Rename metrics component to metric

---

src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/__examples__/baseExtraLargeWithTwoAvatars/baseExtraLargeWithTwoAvatars.html
src/modules/base/avatarGroup/__examples__/baseExtraLargeWithTwoAvatars/baseExtraLargeWithTwoAvatars.js
src/modules/base/avatarGroup/__examples__/baseLargeWithMoreThanTwoAvatars/baseLargeWithMoreThanTwoAvatars.html
src/modules/base/avatarGroup/__examples__/baseLargeWithMoreThanTwoAvatars/baseLargeWithMoreThanTwoAvatars.js
src/modules/base/avatarGroup/__examples__/baseWithMoreThanTwoAvatars/baseWithMoreThanTwoAvatars.html
src/modules/base/avatarGroup/__examples__/baseWithMoreThanTwoAvatars/baseWithMoreThanTwoAvatars.js
src/modules/base/avatarGroup/__examples__/baseWithTwoAvatars/baseWithTwoAvatars.html
src/modules/base/avatarGroup/__examples__/baseWithTwoAvatars/baseWithTwoAvatars.js
src/modules/base/avatarGroup/__examples__/grid/grid.html
src/modules/base/avatarGroup/__examples__/grid/grid.js
src/modules/base/avatarGroup/__examples__/gridSmall/gridSmall.html
src/modules/base/avatarGroup/__examples__/gridSmall/gridSmall.js
src/modules/base/avatarGroup/__examples__/gridWithPresence/gridWithPresence.html
src/modules/base/avatarGroup/__examples__/gridWithPresence/gridWithPresence.js
src/modules/base/avatarGroup/__examples__/listWithXxLargeAvatars/listWithXxLargeAvatars.html
src/modules/base/avatarGroup/__examples__/listWithXxLargeAvatars/listWithXxLargeAvatars.js
src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.js

Added 'name' property to identify an avatar in items. 
Added 'name' parameter to 'avatarclick' event. 
Added 'targetName' parameter to 'avataractionclick' event.

[feature](abc-646): Add name to avatar group items

---

src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Prevented the deselection of an option, when the input is not multi-select, and the type is `button`

[fix] (ABC-668): Prevent deselection of button type radio choice set

---

src/modules/base/calendar/__docs__/calendar.stories.js
src/modules/base/calendar/__examples__/calendar.js
src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.html
src/modules/base/calendar/calendar.js

**Calendar**
- Added attribute hide-header

Abc 598 calendar add option to hide navigation

---

src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.js

**Calendar**
- Added public methods:  nextMonth, previousMonth, goToDate(date)
- Parameters: date: Date, String, Object - Date to navigate to. Can be a Date object or ISO8601 date string)

Abc 602 calendar add methods

---

src/modules/base/activityTimeline/horizontalActivityTimeline.js

Horizontal Activity Timeline
- Fix drag of interval rectangle on scroll axis.
- Fix drag of interval's bounds on scroll axis.

[Fix](ABC-704): Horizontal Activity Timeline - Fix drag of interval rectangle on website

---

src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/buttonMenu/__examples__/buttonMenuBase.js
src/modules/base/buttonMenu/__examples__/buttonMenuIllustration.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/storybookWrappers/buttonMenu/base.html
src/modules/base/storybookWrappers/buttonMenu/base.js
src/modules/base/storybookWrappers/buttonMenu/illustration.html
src/modules/base/storybookWrappers/buttonMenu/illustration.js

- Added hide down arrow attribute to storybook and wrappers

[fix](ABC-693): Added hide down arrow attribute to stories and wrapper

---

src/modules/base/dialog/dialog.js
src/modules/base/wizard/__tests__/wizard.test.js
src/modules/base/wizard/base.html
src/modules/base/wizard/quickActionPanel.html
src/modules/base/wizard/wizard.js

**Wizard**
- Only display header markup if  title, title slot or icon name

[fix](ABC-702): Added show header

---

src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/profileCard/__docs__/profileCard.stories.js
src/modules/base/profileCard/__examples__/extraLargeSquare/extraLargeSquare.html
src/modules/base/profileCard/__examples__/extraSmallBottomCenter/extraSmallBottomCenter.html
src/modules/base/profileCard/__examples__/largeBottomLeft/largeBottomLeft.html
src/modules/base/profileCard/__examples__/noActions.js
src/modules/base/profileCard/__examples__/profileCard.js
src/modules/base/profileCard/__examples__/smallBottomCenterMobile/smallBottomCenterMobile.html
src/modules/base/profileCard/__examples__/smallTopRight/smallTopRight.html
src/modules/base/profileCard/__tests__/profileCard.test.js
src/modules/base/profileCard/profileCard.js
src/modules/base/storybookWrappers/profileCard/mobileProfileCard.js
src/modules/base/storybookWrappers/profileCard/noActions.html
src/modules/base/storybookWrappers/profileCard/noActions.js
src/modules/base/storybookWrappers/profileCard/profileCard.html
src/modules/base/storybookWrappers/profileCard/profileCard.js

- Changed attribute size to avatarSize

[doc](ABC-686): Profile card - Changed attribute size to avatarSize

---

src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.js

- Fix error when value is a string

[fix](ABC-712): Dual Listbox - Error when value is a string

---

src/modules/base/avatarGroup/avatarGroup.html

- Primary Text, Secondary Text, Tags and Tertiary Text after clicking on view more not displayed

[fix](ABC-719): Avatar group - Display texts in show more

---

src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.html
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevented the dropdown content from being inserted in the DOM, unless the combobox was opened.

[fix] (ABC-723): Insert dropdown in DOM only when opened

---

src/modules/base/pillContainer/__docs__/pillContainer.jsdoc.js
src/modules/base/primitivePill/primitivePill.css

-Added --avonni-pill-color-background-hover

[feat](ABC-717): Pill Container - Add background color hover styling hook

---

src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html

- Added support for "itemclick" event for the vertical mode

[feat](ABC-729): Activity Timeline - Added itemclick event on vertical mode

---

src/modules/base/dualListbox/dualListbox.js
src/modules/base/filterMenu/filterMenu.js
src/modules/base/image/image.js
src/modules/base/inputCounter/inputCounter.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.css
src/modules/base/scopedNotification/__docs__/scopedNotification.jsdoc.js
src/modules/base/separator/separator.css

- Added event.stopPropagation to dual listbox search engine
**Filter menu**
- Added event.stopPropagation to filter menu search engine

Fix abc 727 dual listbox search engine should not search throw selected values

---

src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/dateTimePicker/dateTimePicker.js

- Added support for ISO8601 dates in `disabled-date-times`.

[fix] (ABC-733): Allow string disabled dates in date time picker

---

src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- Set any invalid property to its default value.

[fix][defaults] (ABC-737): Set invalid dates to default values in slider

---

src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js

- Fixed the firing of the `itemclick` event in a grouped timeline.

[fix] (ABC-738): Fix itemclick event in grouped activity timeline

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- Added the `getItemPosition()` method, used to retrieve the size of an item and its position in the viewport.

[feat] (ABC-761): Add getItemPosition() to list

---

src/modules/base/primitiveWizardNavigation/__tests__/primitiveWizardNavigation.test.js
src/modules/base/primitiveWizardNavigation/primitiveWizardNavigation.html
src/modules/base/primitiveWizardNavigation/primitiveWizardNavigation.js
src/modules/base/wizard/wizard.js

**Wizard**
- Fixed the indicator display on small screens. The wizard will now default to a bar indicator if the available space is smaller than 480 pixels.

[fix] (ABC-585): Fix wizard indicator display on small screens

---

src/modules/base/calendar/calendar.css

**Calendar**
- Fixed year combobox being overflown by other elements.

[fix] (ABC-755): Fix calendar year combobox overflown

---

src/modules/base/slider/slider.css
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

Slider
- Vertical responsive slider now takes in account unit and label height for height calculation.

[Bugfix] (ABC-776) slider vertical height calculation error

---

src/modules/base/colorPalette/grid.html
src/modules/base/inputPen/__docs__/inputPen.stories.js
src/modules/base/inputPen/__tests__/inputPen.test.js
src/modules/base/inputPen/inputPen.html
src/modules/base/inputPen/inputPen.js

Input Pen
- Input pen now has full height default palette for color picker
- Mobile now supported
Input Pen
- Fixed ink mode cursor not appearing

[Feature] (ABC-766) input pen improvements

---

src/modules/base/inputPen/inputPen.html
src/modules/base/inputPen/inputPen.js

Input Pen
- Now listening to touch events

[Bugfix] (ABC-766) : touch event listening for input pen

---

src/modules/base/slider/__tests__/slider.test.js

Slider
- Tests for slider are fixed

[Bugfix] (ABC-787) : Tests for slider are fixed

---

src/modules/base/progressIndicator/__examples__/baseWithPopoverHidden/baseWithPopoverHidden.html
src/modules/base/progressIndicator/__examples__/baseWithPopoverVisible/baseWithPopoverVisible.html
src/modules/base/progressIndicator/__examples__/milestones/milestones.html
src/modules/base/progressIndicator/__examples__/milestonesShaded/milestonesShaded.html
src/modules/base/progressIndicator/__examples__/withButtons/withButtons.html
src/modules/base/progressIndicator/progressIndicator.js

**Progress Indicator**
- Fix overflow issue

[fix](ABC-774): Progress Indicator - Overflow Issue

---

src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js

- Fix issue with avatarclick
- Fix issue with avatar details in show more

[fix](ABC-778): Avatar group - Issue with avatar click and avatar details

---

src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/alert/alert.css

**Alert**
- Added border styling hooks
--avonni-alert-color-border
--avonni-alert-sizing-border
--avonni-alert-styling-border

[feat](ABC-730): Alert - Added border styling hooks

---

lwc.config.json
src/modules/base/datatable/__docs__/data.js
src/modules/base/datatable/__examples__/dataTypesFromPtoR/dataTypesFromPtoR.js
src/modules/base/datatable/progressCircle.html
src/modules/base/primitiveCellProgressBar/primitiveCellProgressBar.html
src/modules/base/primitiveCellProgressBar/primitiveCellProgressBar.js
src/modules/base/primitiveCellProgressBar/primitiveCellProgressBar.js-meta.xml
src/modules/base/primitiveCellProgressCircle/primitiveCellProgressCircle.html
src/modules/base/primitiveCellProgressCircle/primitiveCellProgressCircle.js
src/modules/base/primitiveCellProgressCircle/primitiveCellProgressCircle.js-meta.xml

**Datatable**
- Progress bar & progress circle - value is now between 0 and 1 like percent

[fix](ABC-782): Datatable - progress bar & progress circle - value is now between 0 and 1

---

src/modules/base/primitiveAvatar/primitiveAvatar.js

**Avatar**
- Fixed issue with entity icon name when icon name include "_"

[fix](ABC-789): Avatar - Entity Icon name class issue when iconName include "_"

---

src/modules/base/activityTimeline/horizontalActivityTimeline.js

- Fix change of interval's width bug when horizontally scrolling with wheel

[fix](ABC-748): Horizontal Activity Timeline - Fix scroll with wheel issue

---

src/modules/base/inputPen/inputPen.js

Input Pen
- Added check for background canvas height

[Bugfix] (ABC-766) : added check for background canvas height

---

src/modules/base/heroBanner/__docs__/heroBanner.jsdoc.js
src/modules/base/heroBanner/__docs__/heroBanner.stories.js
src/modules/base/heroBanner/__examples__/base/base.html
src/modules/base/heroBanner/__examples__/baseWithBackgroundImg/baseWithBackgroundImg.html
src/modules/base/heroBanner/__examples__/baseWithBackgroundImg/baseWithBackgroundImg.js
src/modules/base/heroBanner/__examples__/heroBanner.js
src/modules/base/heroBanner/__examples__/heroBannerWithButton.js
src/modules/base/heroBanner/__examples__/heroBannerWithSearchBarInDefault.js
src/modules/base/heroBanner/__examples__/heroBannerWithSearchBarInFooter.js
src/modules/base/heroBanner/__examples__/heroBannerWithTwoSlots.js
src/modules/base/heroBanner/__tests__/heroBanner.test.js
src/modules/base/heroBanner/heroBanner.css
src/modules/base/heroBanner/heroBanner.html
src/modules/base/heroBanner/heroBanner.js
src/modules/base/storybookWrappers/heroBanner/heroBanner.html
src/modules/base/storybookWrappers/heroBanner/heroBanner.js
src/modules/base/storybookWrappers/heroBanner/heroBannerWithButton.html
src/modules/base/storybookWrappers/heroBanner/heroBannerWithButton.js
src/modules/base/storybookWrappers/heroBanner/heroBannerWithSearchBarInDefault.html
src/modules/base/storybookWrappers/heroBanner/heroBannerWithSearchBarInDefault.js
src/modules/base/storybookWrappers/heroBanner/heroBannerWithSearchBarInFooter.html
src/modules/base/storybookWrappers/heroBanner/heroBannerWithSearchBarInFooter.js
src/modules/base/storybookWrappers/heroBanner/heroBannerWithTwoSlots.html
src/modules/base/storybookWrappers/heroBanner/heroBannerWithTwoSlots.js

**Hero Banner**
- Change background-color and image-overlay properties for styling hooks

[feat](ABC-792): Hero Banner - Change background-color and image-overlay for styling hooks

---

src/modules/base/primitiveAvatar/__tests__/primitiveAvatar.test.js
src/modules/base/primitiveAvatar/primitiveAvatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.js

**Avatar**
- If action item has no icon, uses action-menu-icon

[fix](ABC-794): Avatar - If action item has no icon uses default icon

---

src/modules/base/avatarGroup/avatarGroup.js

- Fix issue with dropdown menu

[fix](ABC-795): Avatar group - Fix issue with dropdown

---

src/modules/base/activityTimeline/__docs__/data.js
src/modules/base/activityTimeline/__examples__/horizontal/horizontal.html
src/modules/base/activityTimeline/__examples__/horizontal/horizontal.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/__tests__/horizontalActivityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.css
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/activityTimeline/horizontalActivityTimeline.js
src/modules/base/outputData/outputData.css
src/modules/base/outputData/outputData.html
src/modules/base/outputData/outputData.js

**Horizontal activity timeline**
- Add formatted date, description and actions to item's popover

[Feat] (ABC-754):  Add more informations to popover of horizontal activity timeline

---

src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js

**Carousel**
- add event.stopPropagation() to actionclick

[fix](ABC-802): Carousel - add event.stopPropagation() to actionclick

---

src/modules/base/visualPicker/visualPicker.js

fix issue with radio type picker

[fix](ABC-808): Visual picker - fix issue with radio type picker

---

src/modules/base/inputPen/inputPen.js

Input Pen
- Fixed touch even handling for many touches

[fix] (ABC-767) : fixed touch events

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.js

**Slider**
- Max should be 1 when unit is in percentage

[fix](ABC-797): Slider - Max should be 1 when unit is in percentage

---

src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js

No changes from previous package version

[fix] (ABC-810): Revert changes made to button icon variant in list

---

src/modules/base/list/list.html
src/modules/base/list/list.js

Fix for integration in Salesforce. No difference with previous package version.

[fix] (ABC-813): Fix problems with Salesforce locker in list

---

src/modules/base/inputPen/inputPen.css
src/modules/base/inputPen/inputPen.js

Input Pen
- Color palette changed for background color on input pen (Kept greyscale colors)
Input Pen
- On mobile, touches on the drawing area no longer scroll

[Bugfix] (ABC-814) Input pen prevent scrolling on mobile and background color palette change

---

src/modules/base/iconPicker/iconPicker.html
src/modules/base/iconPicker/iconPicker.js
src/modules/base/tabBar/tabBar.html

No changes compared to the previous package version.

[fix] (ABC-818): Fix icon picker popover closing when clicking inside

---

src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js

- Fixed options movement when using Locker on the Salesforce platform.

[fix] (ABC-820): Use dataset instead of role in dual listbox

---

src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js

Same fix as pull request #483.

[fix] (ABC-822): Prevent error with Salesforce Locker and pill container

---

src/modules/base/list/list.js

**List**
- Prevented the list from overflowing its parent horizontally.

[fix] (ABC-825): Prevent horizontal overflow in list

---

src/modules/base/inputPen/inputPen.css
src/modules/base/inputPen/inputPen.html
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.js

**Input pen**
- Fixed header styling hooks
**Vertical Visual picker**
- Fixed background and border styling hooks

[Fix](ABC-824): Vertical visual Picker & Input Pen: Fix styling hooks

---

src/modules/base/expandableSection/__docs__/expandableSection.jsdoc.js
src/modules/base/expandableSection/__tests__/expandableSection.test.js
src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.html
src/modules/base/expandableSection/expandableSection.js
src/modules/base/inputPen/inputPen.css
src/modules/base/inputPen/inputPen.html
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.js

- Fixed figure styling hooks
**Input Pen**
- Fix issue with header styling hooks
- Fix issue with styling hooks when collapsible
--avonni-expandable-section-base-header-color-background
--avonni-expandable-section-shaded-header-color-background

[Fix](ABC-824): base components fix styling hooks

---

src/modules/base/activityTimeline/__tests__/activityTimeline.test.js

- Fix the test error on package publication (line was commented)

[fix](ABC-763): Activity Timeline - Fix the test error on package publication

---

src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/alert/__docs__/alert.stories.js
src/modules/base/alert/__examples__/alert.js
src/modules/base/alert/__tests__/alert.test.js
src/modules/base/alert/alert.css
src/modules/base/alert/alert.html
src/modules/base/alert/alert.js
src/modules/base/pageHeader/__docs__/pageHeader.stories.js
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.css
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.js
src/modules/base/storybookWrappers/alert/alert.html
src/modules/base/storybookWrappers/alert/alert.js

**Alert**
- Added attribute icon-size
- Added styling hook for horizontal content alignment

[Feat](ABC-765): Alert - Add new attribute and styling hook

---

src/modules/base/calendar/calendar.js

**Calendar**
- Added validation for date-labels

[fix](ABC-828): Calendar - Add validation for date labels

---

package-lock.json
src/modules/base/alert/__tests__/alert.test.js
src/modules/base/colorPicker/__docs__/colorPicker.stories.js
src/modules/base/colorPicker/__examples__/colorPicker.js
src/modules/base/colorPicker/__tests__/colorPicker.test.js
src/modules/base/colorPicker/colorPicker.html
src/modules/base/colorPicker/colorPicker.js

- Added `hide-clear-icon` attribute.

[feat] (ABC-830): Add hide-clear-icon attribute to color picker

---

src/modules/base/tabBar/__tests__/tabBar.test.js
src/modules/base/tabBar/tabBar.js

**Tab Bar**
- Fixed the update of any property after the component has been inserted into the DOM.

[fix] (ABC-832): Allow update of tab bar properties after first render

---

src/modules/base/primitiveProgressStep/__tests__/primitiveProgressStep.test.js
src/modules/base/primitiveProgressStep/primitiveProgressStep.html
src/modules/base/primitiveProgressStep/primitiveProgressStep.js
src/modules/base/progressIndicator/__docs__/progressIndicator.jsdoc.js
src/modules/base/progressIndicator/__tests__/progressIndicator.test.js
src/modules/base/progressIndicator/progressIndicator.html

**Progress Indicator**
- Step - Delete unused buttonTitle attribute

[fix](ABC-833): Progress indicator step - delete button title attribute

---

src/modules/base/storybookWrappers/verticalProgressIndicator/verticalProgressIndicator.html
src/modules/base/storybookWrappers/verticalProgressIndicator/verticalProgressIndicator.js
src/modules/base/verticalProgressIndicator/__docs__/verticalProgressIndicator.stories.js
src/modules/base/verticalProgressIndicator/__examples__/complete/complete.html
src/modules/base/verticalProgressIndicator/__examples__/complete/complete.js
src/modules/base/verticalProgressIndicator/__examples__/verticalProgressIndicator.js
src/modules/base/verticalProgressIndicator/__tests__/verticalProgressIndicator.test.js
src/modules/base/verticalProgressIndicator/verticalProgressIndicator.js

**Vertical Progress Indicator**
- Added mark-as-complete attribute

[Feat](ABC-835): Vertical Progress Indicator - Add markAsComplete attribute

---

src/modules/base/verticalProgressStep/verticalProgressStep.html
src/modules/base/verticalProgressStep/verticalProgressStep.js

**Vertical Progress Step**
- Added slot label

[feat](ABC-838): Vertical Progress Step - Added slot label

---

src/modules/base/path/__docs__/path.stories.js
src/modules/base/path/path.js
src/modules/base/progressIndicator/__docs__/progressIndicator.stories.js
src/modules/base/storybookWrappers/verticalProgressIndicator/verticalProgressIndicator.html
src/modules/base/storybookWrappers/verticalProgressIndicator/verticalProgressIndicator.js
src/modules/base/verticalProgressIndicator/__docs__/verticalProgressIndicator.stories.js
src/modules/base/verticalProgressIndicator/__examples__/nonLinear/nonLinear.html
src/modules/base/verticalProgressIndicator/__examples__/nonLinear/nonLinear.js
src/modules/base/verticalProgressIndicator/__examples__/verticalProgressIndicator.js
src/modules/base/verticalProgressIndicator/__tests__/verticalProgressIndicator.test.js
src/modules/base/verticalProgressIndicator/verticalProgressIndicator.js

**Vertical Progress Indicator**
- Added attribute format to choose between progress format linear and non-linear
- Added attribute completed-steps

[Feat](ABC-837) Vertical progress indicator - Added attributes format and completed steps

---

src/modules/base/combobox/__docs__/combobox.jsdoc.js
src/modules/base/combobox/__docs__/data.js
src/modules/base/combobox/__examples__/base/base.js
src/modules/base/combobox/__examples__/customSearch/customSearch.js
src/modules/base/combobox/__examples__/grouped/grouped.js
src/modules/base/combobox/__examples__/loading/loading.js
src/modules/base/combobox/__examples__/lookup/lookup.js
src/modules/base/combobox/__examples__/multiLevelGroups/multiLevelGroups.js
src/modules/base/combobox/__examples__/multiSelect/multiSelect.js
src/modules/base/combobox/__examples__/readOnly/readOnly.js
src/modules/base/combobox/__examples__/readOnlyMultiSelect/readOnlyMultiSelect.js
src/modules/base/combobox/__examples__/scopes/scopes.js
src/modules/base/combobox/__examples__/scopesWithIcons/scopesWithIcons.js
src/modules/base/combobox/__examples__/verticalSelectedOptions/verticalSelectedOptions.js
src/modules/base/combobox/__tests__/data.js
src/modules/base/primitiveCombobox/__tests__/data.js
src/modules/base/primitiveCombobox/option.js
src/modules/base/primitiveCombobox/primitiveCombobox.html
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.html

**Combobox**
-  Changed avatar src and avatar fallback icon name for avatar object

[Feat](ABC-841) - Combobox change avatar src and avatar fallback icon name for avatar object

---

src/modules/base/inputCounter/__tests__/inputCounter.test.js
src/modules/base/inputCounter/inputCounter.html
src/modules/base/inputCounter/inputCounter.js
src/modules/base/inputCounter/numberFormat.js
src/modules/base/pagination/__tests__/pagination.test.js
src/modules/base/pagination/pagination.css
src/modules/base/pagination/pagination.html
src/modules/base/pagination/pagination.js
src/modules/base/primitiveComboboxGroup/__tests__/data.js
src/modules/base/rating/__docs__/rating.stories.js
src/modules/base/rating/__examples__/singleSelectionLabelStacked/singleSelectionLabelStacked.html
src/modules/base/rating/__examples__/singleSelectionLabelStacked/singleSelectionLabelStacked.js
src/modules/base/rating/__tests__/rating.test.js
src/modules/base/rating/item.js
src/modules/base/rating/rating.css
src/modules/base/rating/rating.html
src/modules/base/rating/rating.js

**Rating**
- Fixed the hover not following the mouse when an icon name is set.
- Fixed the selected icons color when an icon name is set.
- Fixed the variant always displayed as `label-inline`.

[refactor][fix] (ABC-849): Remove document.createElement('style')

---

src/modules/base/inputPen/__docs__/inputPen.stories.js
src/modules/base/inputPen/__examples__/inputPen.js
src/modules/base/inputPen/__tests__/inputPen.test.js
src/modules/base/inputPen/inputPen.js

InputPen
- Input pen added background color attribute

[Feature] (ABC-836): Input pen added background color attribute

---

src/modules/base/blockquote/__docs__/blockquote.jsdoc.js
src/modules/base/blockquote/blockquote.css

**Blockquote**
- Added new styling hooks for height, width and overflow

[feat](ABC-775): Blockquote - Added new styling hooks

---

src/modules/base/buttonIconPopover/buttonIconPopover.html
src/modules/base/buttonIconPopover/buttonIconPopover.js
src/modules/base/buttonPopover/buttonPopover.html
src/modules/base/buttonPopover/buttonPopover.js

[fix](ABC-854): Button Icon Popover & Button Popover - Remove deprecated keypress

---

jest-mock/components/base/primitivePill/primitivePill.js
src/modules/base/pillContainer/__docs__/data.js
src/modules/base/pillContainer/__docs__/pillContainer.stories.js
src/modules/base/pillContainer/__examples__/collapsible/collapsible.html
src/modules/base/pillContainer/__examples__/collapsible/collapsible.js
src/modules/base/pillContainer/__examples__/singleLine/singleLine.html
src/modules/base/pillContainer/__examples__/singleLine/singleLine.js
src/modules/base/pillContainer/__examples__/sortable/sortable.html
src/modules/base/pillContainer/__examples__/sortableSingleLine/sortableSingleLine.html
src/modules/base/pillContainer/__examples__/sortableSingleLine/sortableSingleLine.js
src/modules/base/pillContainer/__tests__/pillContainer.test.js
src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js
src/modules/base/primitivePill/__tests__/primitivePill.test.js
src/modules/base/primitivePill/primitivePill.css
src/modules/base/primitivePill/primitivePill.html
src/modules/base/primitivePill/primitivePill.js

- Allowed `single-line` pill container to be collapsed. Implemented an automatic infinite load for the collapsed `single-line` pills.
- Improved the performance, by preventing the pills from being rendered if they are collapsed.
- Allowed sorting items when they are collapsed, by expanding the container on hover on the button.

[feat] (ABC-846): Allow collapsed single-line pill container

---

src/modules/base/filterMenu/filterMenu.js

No changes compared to last package version.

[fix] (ABC-864): Fix filter menu closing on click on range

---

src/modules/base/list/list.css

**List**
- Fixed `divider` attribute when set to bottom.

[fix] (ABC-865): Fix list bottom divider

---

src/modules/base/combobox/__docs__/data.js
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/__tests__/data.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/primitivePill/primitivePill.js

**Combobox**
- Added support for options with a number as a value.

[feat] (ABC-868): Add support for number option value in combobox

---

src/modules/base/pillContainer/__tests__/pillContainer.test.js
src/modules/base/pillContainer/pillContainer.js

[feat] (ABC-861): Add expand event to pill container

---

src/modules/base/activityTimeline/activityTimeline.js

- Fixed the sorting (ascendant or descendant) of the groups.

[fix][refactor] (ABC-872): Fix activity timeline yearly group by

---

src/modules/base/avatar/avatar.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/visualPicker/visualPicker.html

**Avatar, Vertical visual picker & Visual picker**
- If no label, no tag

[fix](ABC-881): Avatar & Vertical Visual Picker - Added validation on label for tags

---

src/modules/base/blockquote/__docs__/blockquote.jsdoc.js
src/modules/base/blockquote/blockquote.css

**Blockquote**
- Added border radius styling hook

[feat](ABC-888): Blockquote - Added border radius styling hook

---

src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.js
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.css
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.html

- Icon styling hooks should be applied for completed and info only state

[Fix](ABC-890): Visual picker link - icon styling hooks should be applied for completed and info only state

---

src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.html
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.html
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/scheduleBase.js

**Scheduler**
- Improved performance of the timeline display, when used in Salesforce with the Lightning Locker service enabled.

[fix] (ABC-892): Improve scheduler speed when used with Lightning Locker

---

src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/primitiveSchedulerHeaderGroup/primitiveSchedulerHeaderGroup.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.html
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/scheduler/__docs__/scheduler.jsdoc.js
src/modules/base/schedulerSharedStyle/schedulerSharedStyle.css
src/modules/base/schedulerUtils/scheduleBase.js

**Scheduler**
- Added styling hooks for border color.

[feat] (ABC-897): Add border styling hooks to scheduler

---

src/modules/base/primitiveSchedulerAgenda/dayGroup.js
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.html
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.html
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/scheduler/scheduler.html
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/scheduleBase.js

**Scheduler**
- Added the `scheduleclick` event.

[feat] (ABC-901): Add scheduleclick event to scheduler

---

src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html

- Deleted additional margin around fields

[fix](ABC-902): Activity Timeline - Delete margin around fields

---

src/modules/base/avatar/avatar.css
src/modules/base/avatar/avatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.css
src/modules/base/primitiveAvatar/primitiveAvatar.js

**Avatar**
- Fixed issue with tags alignment
- Replaced SLDS-avatar by avonni-avatar

[Fix](ABC-907): Avatar - Replace slds-avatar class by avonni-avatar

---

src/modules/base/colorPicker/colorPicker.css
src/modules/base/colorPicker/colorPicker.html
src/modules/base/colorPickerPanel/colorPickerPanel.js

- Replace slds-tabs classes by avonni-tabs classes

[Fix](ABC-908): Color picker - Replace slds-tabs class

---

src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.html

No changes compared to the previous package version.

[fix] (ABC-913): Pass time zone to scheduler agenda side panel calendar

---

src/modules/base/progressCircle/progressCircle.html
src/modules/base/progressCircle/progressCircle.js

**Progress Circle**
- Hide title div when no title

[fix](ABC-914): Progress circle - Hide div when no title

---

src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- When an item is dragged, allowed the release anywhere in the window, instead of having to release it inside the list.

[fix] (ABC-917): Allow dragged list element release anywhere

---

src/modules/base/datatable/badge.html
src/modules/base/datatable/datatable.js
src/modules/base/datatable/dynamicIcon.html
src/modules/base/datatable/image.html
src/modules/base/datatable/progressCircle.html
src/modules/base/datatable/progressRing.html
src/modules/base/datatable/qrcode.html

**Data table**
- Added cellAttributes to custom cells
Badge
Dynamic Icon
Image
Progress Ring
Progress Circle
QR Code

[feat](ABC-919): Datatable - Added cellAttributes to custom cells

---

src/modules/base/chip/__docs__/chip.jsdoc.js
src/modules/base/chip/chip.css
src/modules/base/chip/chip.js
src/modules/base/chipContainer/__docs__/chipContainer.jsdoc.js
src/modules/base/chipContainer/__docs__/chipContainer.stories.js
src/modules/base/chipContainer/__docs__/data.js
src/modules/base/chipContainer/__examples__/chipContainer.js
src/modules/base/chipContainer/__examples__/maxWidthChipContainer.js
src/modules/base/chipContainer/__examples__/singleLineCollapsed/singleLineCollapsed.html
src/modules/base/chipContainer/__examples__/singleLineCollapsed/singleLineCollapsed.js
src/modules/base/chipContainer/__examples__/singleLineSortable/singleLineSortable.html
src/modules/base/chipContainer/__examples__/singleLineSortable/singleLineSortable.js
src/modules/base/chipContainer/__tests__/chipContainer.test.js
src/modules/base/chipContainer/chipContainer.css
src/modules/base/chipContainer/chipContainer.html
src/modules/base/chipContainer/chipContainer.js
src/modules/base/pillContainer/__tests__/pillContainer.test.js
src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js
src/modules/base/primitiveChip/__tests__/primitiveChip.test.js
src/modules/base/primitiveChip/primitiveChip.css
src/modules/base/primitiveChip/primitiveChip.html
src/modules/base/primitiveChip/primitiveChip.js
src/modules/base/storybookWrappers/chipContainer/maxWidthChipContainer.html
src/modules/base/storybookWrappers/chipContainer/maxWidthChipContainer.js

**Chip Container**
- Added attribute single line
- Added attribute sortable
- Added focus method
- Added blur, expand, focus and reorder events
- Added Styling hooks for chip and container

[Feat](ABC-918): Chip container - Add new attributes

---

src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/__examples__/baseWithMoreThanTwoAvatars/baseWithMoreThanTwoAvatars.js
src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.html
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/primitiveAvatar/primitiveAvatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.js

- Added infinite loading to the hidden items dropdown.

[feat] (ABC-920): Add infinite loading to avatar group dropdown menu

---

src/modules/base/rating/__tests__/rating.test.js
src/modules/base/rating/item.js
src/modules/base/rating/rating.css
src/modules/base/rating/rating.html
src/modules/base/rating/rating.js

**Rating**
- Changed UI of rating when read-only. Selected stars are colored but component is disabled

[fix](ABC-929): Rating - Changed UI of rating when read-only

---

src/modules/base/chip/__tests__/chip.test.js
src/modules/base/chip/chip.html
src/modules/base/chip/chip.js

**Chip**
- Fixed the addition of an avatar to the chip, after the component has been inserted in the DOM.

[fix] (ABC-927): Fix avatar addition after first insertion of the chip

---

src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.js

- Fix issue with button menu default value. The value defaults to neutral when label and border without

[fix](ABC-925): Button menu - Fix issue with default variant

---

src/modules/base/datatable/datatable.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.html

**Datatable**
- Fix min and max length for textarea type of cell

[fix](ABC-937): Datatable - Fix min and max length for textarea

---

package-lock.json
src/modules/base/pillContainer/pillContainer.html

- Opened the single line popover to the right, to prevent overflow.

[fix] (ABC-938): Open the pill cont. single line popover to the right

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/horizontalActivityTimeline.css
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/activityTimeline/verticalActivityTimeline.css
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/shared.css

- Added styling hooks for title and icon
- Renamed icon's styling hooks

[Feat](ABC-940) Activity timeline - Add styling hooks

---

lwc.config.json
src/modules/base/layout/__docs__/layout.jsdoc.js
src/modules/base/layout/__docs__/layout.stories.js
src/modules/base/layout/__examples__/base/base.html
src/modules/base/layout/__examples__/base/base.js
src/modules/base/layout/__examples__/layout.js
src/modules/base/layout/__examples__/multipleRows/multipleRows.html
src/modules/base/layout/__examples__/multipleRows/multipleRows.js
src/modules/base/layout/__examples__/reverseColumns/reverseColumns.html
src/modules/base/layout/__examples__/reverseColumns/reverseColumns.js
src/modules/base/layout/__tests__/layout.test.js
src/modules/base/layout/layout.css
src/modules/base/layout/layout.html
src/modules/base/layout/layout.js
src/modules/base/layout/layout.js-meta.xml
src/modules/base/layoutItem/__docs__/layoutItem.jsdoc.js
src/modules/base/layoutItem/__tests__/layoutItem.test.js
src/modules/base/layoutItem/layoutItem.css
src/modules/base/layoutItem/layoutItem.html
src/modules/base/layoutItem/layoutItem.js
src/modules/base/layoutItem/layoutItem.js-meta.xml
src/modules/base/storybookWrappers/layout/layout.html
src/modules/base/storybookWrappers/layout/layout.js

**Layout and Layout Item**
- Created the layout and layout item components.

[feat] (ABC-936): Create the layout and layout item components

---

src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.html
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/primitiveDatatableIeditTypeFactoryCustom.js

**Datatable**
- Fix issue when massEdit and combobox

[fix](ABC-948): Datatable - fix combobox when massEditEnabled

---

src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js

**Datatable**
- When combobox is multiselect, keep order for displayed value

[fix](ABC-954): Datatable - Combobox multiselect keep the value order

---

src/modules/base/datatable/combobox.html
src/modules/base/datatable/datatable.js
src/modules/base/primitiveCellColorPicker/primitiveCellColorPicker.html
src/modules/base/primitiveCellColorPicker/primitiveCellColorPicker.js
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.html
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveCellCounter/primitiveCellCounter.html
src/modules/base/primitiveCellCounter/primitiveCellCounter.js
src/modules/base/primitiveCellDateRange/primitiveCellDateRange.html
src/modules/base/primitiveCellDateRange/primitiveCellDateRange.js
src/modules/base/primitiveCellLookup/primitiveCellLookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.js
src/modules/base/primitiveCellRichText/primitiveCellRichText.html
src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.html
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js

**Data Table**
- Fix issue with popover alignment

[fix](ABC-960): Datatable - Inline editing - Fix issue with popover alignment

---

src/modules/base/filterMenu/__docs__/filterMenu.stories.js
src/modules/base/filterMenu/__examples__/filterMenu.js
src/modules/base/filterMenu/__examples__/infiniteLoading.js
src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenu/filterMenuVertical.css
src/modules/base/filterMenu/filterMenuVertical.html
src/modules/base/filterMenuGroup/__docs__/data.js
src/modules/base/filterMenuGroup/__docs__/filterMenuGroup.jsdoc.js
src/modules/base/filterMenuGroup/__docs__/filterMenuGroup.stories.js
src/modules/base/filterMenuGroup/__tests__/data.js
src/modules/base/filterMenuGroup/__tests__/filterMenuGroup.test.js
src/modules/base/filterMenuGroup/filterMenuGroup.html
src/modules/base/filterMenuGroup/filterMenuGroup.js
src/modules/base/filterMenuGroup/menu.js
src/modules/base/storybookWrappers/filterMenu/infiniteLoading.html
src/modules/base/storybookWrappers/filterMenu/infiniteLoading.js

**Filter Menu & Filter Menu Group**
- Added collapsible and closed attribute

[feat](ABC-963): Filter Menu - Added collapsible and closed attributes

---

src/modules/base/tabBar/__docs__/tabBar.jsdoc.js
src/modules/base/tabBar/__docs__/tabBar.stories.js
src/modules/base/tabBar/__examples__/base/base.html
src/modules/base/tabBar/__examples__/base/base.js
src/modules/base/tabBar/__examples__/defaultTab/defaultTab.html
src/modules/base/tabBar/__examples__/defaultTab/defaultTab.js
src/modules/base/tabBar/__examples__/tabBar.js
src/modules/base/tabBar/__examples__/tabsHidden/tabsHidden.html
src/modules/base/tabBar/__examples__/tabsHidden/tabsHidden.js
src/modules/base/tabBar/__tests__/tabBar.test.js
src/modules/base/tabBar/tabBar.html
src/modules/base/tabBar/tabBar.js

**Tab Bar**
- Added `items` attribute
- Set `labels` attribute as deprecated

[feat](ACB-181): Add items attribute and set labels as deprecated

---

src/modules/base/datatable/datatable.js

**Datatable**
- Fixed issue with cellchange event

[fix](ABC-964): Datatable - Fixed issue with cellchange event

---

src/modules/base/datatable/datatable.js
src/modules/base/treeGrid/__docs__/treeGrid.stories.js
src/modules/base/treeGrid/__examples__/treeGrid.js
src/modules/base/treeGrid/treeGrid.html
src/modules/base/treeGrid/treeGrid.js

**Tree Grid**
- Added new attributes
- columnWidthsMode
- hideTableHeader
- maxRowSelection
- resizeStep

[feat](ABC-950): Tree Grid - Added new attributes

---

src/modules/base/pagination/__tests__/pagination.test.js
src/modules/base/pagination/pagination.html
src/modules/base/pagination/pagination.js

**Pagination**
- Updated the component so a click on an ellipsis button moves the navigation to the closest hidden page.

[feat] (ABC-962): Go to closest page on click on pagination ellipsis

---

src/modules/base/combobox/__docs__/combobox.jsdoc.js
src/modules/base/combobox/__docs__/data.js
src/modules/base/combobox/__examples__/lookup/lookup.js
src/modules/base/primitiveCombobox/option.js
src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/primitiveComboboxGroup/__tests__/data.js
src/modules/base/primitiveComboboxGroup/__tests__/primitiveComboboxGroup.test.js
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.css
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.html
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.js

**Combobox**
- Add `disabled` attribute to the combobox options

[feat](ACB-975): Add disabled attribute to combobox options

---

.storybook/manager.js
jest-mock/components/base/combobox/combobox.js
jest-mock/components/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/combobox/__docs__/combobox.stories.js
src/modules/base/combobox/__examples__/combobox.js
src/modules/base/combobox/__examples__/infiniteLoadingCombobox.js
src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.html
src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/storybookWrappers/combobox/combobox.html
src/modules/base/storybookWrappers/combobox/combobox.js

**Combobox**
- Add attribute `hideOptionsUntilSearch`

[Feat](FSC-643) Combobox - Option to display combobox options only when the user enters a value

---

src/modules/base/image/__docs__/image.jsdoc.js
src/modules/base/image/__tests__/image.test.js
src/modules/base/image/image.css
src/modules/base/image/image.html
src/modules/base/image/image.js

[fix] (ABC-992): fixed compare img height

---

src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/__tests__/visualPickerLink.test.js
src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.css
src/modules/base/visualPickerLink/visualPickerLink.html
src/modules/base/visualPickerLink/visualPickerLink.js
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.css
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.html

[refactor] (ABC-989): removed <a> tag when disabled

---

src/modules/base/utilsPrivate/fontCase.js
src/modules/base/utilsPrivate/utilsPrivate.js

[feat] (ABC-995): Add font case utils to use in FSC

---

src/modules/base/kanban/__docs__/kanban.jsdoc.js
src/modules/base/kanban/__docs__/kanban.stories.js
src/modules/base/kanban/__examples__/avatar/avatar.html
src/modules/base/kanban/__examples__/base/base.html
src/modules/base/kanban/__examples__/disabledColumnDrag/disabledColumnDrag.html
src/modules/base/kanban/__examples__/fieldLabelInline/fieldLabelInline.html
src/modules/base/kanban/__examples__/fieldLabelInline/fieldLabelInline.js
src/modules/base/kanban/__examples__/hideHeader/hideHeader.html
src/modules/base/kanban/__examples__/kanban.js
src/modules/base/kanban/__examples__/subGroups/subGroups.html
src/modules/base/kanban/__tests__/data.js
src/modules/base/kanban/__tests__/kanban.test.js
src/modules/base/kanban/kanban.html
src/modules/base/kanban/kanban.js
src/modules/base/kanban/kanbanSubGroups.html
src/modules/base/storybookWrappers/kanban/kanban.html
src/modules/base/storybookWrappers/kanban/kanban.js

**Kanban**
- Added `field-attributes` attribute.
- Updated the examples.

[feat] (ABC-1000): Kanban - Add attribute "fieldAttributes"

---

src/modules/base/kanban/__docs__/kanban.jsdoc.js
src/modules/base/kanban/__tests__/kanban.test.js
src/modules/base/kanban/kanban.js
src/modules/base/kanban/shared.css

Kanban
- Default column sizing min width is now 18rem instead of 14rem.
Kanban
- Added `columnchange` event

[feat] (ABC-1004): Kanban - Add columnchange event

---

src/modules/base/metric/__docs__/metric.jsdoc.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.css
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js
src/modules/base/primitiveMetric/primitiveMetric.html

**Metric**
- Added a line clamp to the label and description. The line clamps are customizable through two styling hooks.
**Metric**
- Improved the responsiveness of the component, by adding truncation to the texts, and the ability to drop on several lines if needed.

[feat] (ABC-1006): Add styling hooks and improve metric responsiveness

---

src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.js

- Removed background when completed

[fix] (ABC-1002): removed background when completed

---

src/modules/base/image/__tests__/image.test.js
src/modules/base/image/image.css
src/modules/base/image/image.html
src/modules/base/image/image.js
src/modules/base/image/magnifier.js

**Image**
- Fix thumbnail not applied to compare image
- Fix border image radius not working

[fix] (ABC-998): fixed thumbnail issue with cmp img

---

src/modules/base/layoutItem/__tests__/layoutItem.test.js
src/modules/base/layoutItem/layoutItem.js

**Layout Item**
- Fixed an `order` update after the component has been inserted into the DOM.

[fix] (ABC-1009): Fix layout item order update after first connexion

---

src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.html
src/modules/base/filterMenu/filterMenu.js

- Added a message in the filter popover when the items are empty and the filter menu is not loading.

[feat] (ABC-1013): Show no result message when no items

---

src/modules/base/pillContainer/__docs__/pillContainer.jsdoc.js
src/modules/base/primitivePill/primitivePill.css

- Added missing styling hooks
--avonni-pill-styling-border
--avonni-pill-color-border-hover
--avonni-pill-text-color-hover

[fix](ABC-1015): Pill Container - Added missing styling hooks

---

src/modules/base/kanban/group.js
src/modules/base/kanban/groupBuilder.js
src/modules/base/kanban/kanban.js
src/modules/base/kanban/kanbanSubGroups.css
src/modules/base/kanban/shared.css
src/modules/base/kanban/tile.js

**Kanban**
- Fixed summarize styling hooks
- Fixed scrollbar visibility
- Fixed issue with the summarize field
- Fixed issue with column alignment in Path variant

[fix](ABC-1012): Kanban - Fix UI issues

---

src/modules/base/filterMenu/__docs__/filterMenu.stories.js
src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.html
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenu/item.js
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js
src/modules/base/primitivePill/__tests__/primitivePill.test.js
src/modules/base/primitivePill/primitivePill.html

- Allowed rich text in the items labels.
- Allowed rich text in the options labels when the type is `default`.
- Allowed rich text in the pills labels.

[feat] (ABC-1014): Allow rich text as filter menu item label

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.js

-  Fix deprecated not being supported and border when stretch

[fix](FSC-1007): Input choice set - Fix deprecated not being supported and border when stretch

---

src/modules/base/utilsPrivate/fontCase.js

No changes compared to previous version

[fix] (ABC-1018): Fix camelCase() function in utils

---

src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/visualPicker.css

- Added styling hooks for the description
- `--avonni-visual-picker-description-line-clamp`
- `--avonni-visual-picker-item-description-alignment`
- `--avonni-visual-picker-item-description-line-clamp`
- Added styling hooks for the tag
- `--avonni-visual-picker-tag-label-font-size`
- `--avonni-visual-picker-tag-label-font-style`
- `--avonni-visual-picker-tag-label-font-weight`
- `--avonni-visual-picker-tag-sizing-border`
- `--avonni-visual-picker-tag-styling-border`
- `--avonni-visual-picker-tag-radius-border`
- `--avonni-visual-picker-tag-line-height`
- Added text, background and border color styling hooks for each variant
- Alt-inverse
- Base
- Brand
- Error
- Info
- Inverse
- Offline
- Success
- Warning

[feat] (ABC-1017): Visual Picker - Add styling hooks

---

src/modules/base/kanban/kanban.html
src/modules/base/kanban/kanban.js
src/modules/base/kanban/kanbanSubGroups.html

**Kanban**
- Fixed the auto scroll in the path variant
- Fixed an issue with the drag and drop not working properly when scrolling

[fix] (ABC-1021) Kanban - Auto scrolling not working for Path Variant

---

src/modules/base/primitiveCellCheckboxButton/primitiveCellCheckboxButton.js
src/modules/base/primitiveCellRating/primitiveCellRating.js
src/modules/base/primitiveCellSlider/primitiveCellSlider.js
src/modules/base/primitiveCellToggle/primitiveCellToggle.js

**Data Table - Rating, CheckboxButton, Slider, Toggle**
- dispactch cellchangecustom onchange

[fix](ABC-1027): Data Table - dispactch cellchangecustom

---

src/modules/base/combobox/combobox.js

**Data Table - Combobox**
- Added a function to split the string if there is delimiters

[fix](ABC-1024): Data Table - Added a function to split the string value if there is delimiters

---

src/modules/base/list/list.html

**List**
- Deleted stopPropogation on click for title link and info labels link

[fix](ABC-1028): List - Deleted stopPropogation on click for title link and info labels link

---

src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.js

**Combobox**
- Fix issue with delimiters

[fix](ABC-1033): Combobox - Fix issue with delimiters

---

src/modules/base/inputCounter/__docs__/inputCounter.stories.js
src/modules/base/inputCounter/__examples__/inputCounter.js
src/modules/base/inputCounter/__tests__/inputCounter.test.js
src/modules/base/inputCounter/inputCounter.js

**Input Counter**
- Added tests

Feat abc 1029 input counter add alignment options and hide value

---

src/modules/base/buttonIconPopover/__docs__/buttonIconPopover.jsdoc.js
src/modules/base/buttonIconPopover/buttonIconPopover.css
src/modules/base/buttonIconPopover/buttonIconPopover.html

**Button Icon Popover**
- Added styling hook for height --avonni-button-icon-popover-sizing-height

[feat](ABC-1032): Button Icon Popover - Added styling hook for height

---

src/modules/base/inputChoiceSet/inputChoiceSet.js

- Checkboxes not properly align for horizontal multiple rows and checkPosition right

[fix](ABC-1042): Input Choice Set - Fix  Checkboxes not properly align for horizontal multiple rows

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.md
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added new type attributes to toggle (messageToggleActive, messageToggleInactive, messageWhenValueMissing, size)
- Added new option attribute (hide label)

[feat](ABC-1043): Input Choice Set - Added new type attributes to toggle

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added line clamp styling hook for option's label
- Fix issue with horizontal alignment

[Fix](ABC-1046): Input Choice Set - Fix issue with horizontal alignment 

---

src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js

- Display "+..." when overflow
- Responsiveness for tags not working properly when click on "Show More"

(ABC-1038): Avatar Group responsiveness

---

src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.css
src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.html
src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.js
src/modules/base/visualPicker/__docs__/data.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Fix figure title issue
- Fix avatar alignment issue

[fix] (ABC-1050): Visual Picker - Fix issue with figure title

---

src/modules/base/verticalVisualPicker/verticalVisualPicker.css

- Fixed styling issue on Salesform platform
- Removed hover color for disabled items

[fix] (ABC-1049): Vertical Visual Picker - Fix styling issue in Run mode on the Salesforce platform

---

src/modules/base/verticalVisualPicker/verticalVisualPicker.js

- Removed left and right border if the avatar is not set

[feat](ABC-1052): Remove left and right border if avatar is not set

---

src/modules/base/visualPicker/__tests__/data.js
src/modules/base/visualPicker/__tests__/visualPicker.test.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Fixed an issue with the figure image size and height

[fix] (ABC-1051): Visual-Picker - Fix issue with figure image size and height

---

src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.html
src/modules/base/expandableSection/expandableSection.js

- Support "compact" mode
- Fix text-color on hover styling hooks not working

[Feat](ABC-1053): Expandable Section - Support comfy and compact

---

src/modules/base/chipContainer/chipContainer.html
src/modules/base/colorPalette/colorPalette.js
src/modules/base/colorPicker/standard.html
src/modules/base/filterMenu/filterMenu.html
src/modules/base/focusTrap/focusUtils.js
src/modules/base/iconPicker/iconPicker.html
src/modules/base/inputDateRange/inputDateRange.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/scheduler/scheduler.html

No changes compared to the last package version.

[fix] (ABC-1060): Fix focus trap when used with Salesforce Locker

---

src/modules/base/primitiveCellBadge/primitiveCellBadge.html

**Data Table**
-  Hide badge if empty of null

[fix](ABC-1063): Data table - Hide badge if empty of null

---

src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.css
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.css

- Added new styling hooks for complete

[feat](ABC-1062): Visual Picker Link - Added new styling hooks

---

src/modules/base/primitiveCarouselItem/noTag.html
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js
src/modules/base/primitiveCarouselItem/tag.html

**Carousel**
- event stop propagation for button menu click

[fix](ABC-1065): Carousel - event stop propagation for button menu click

---

src/modules/base/filterMenu/filterMenu.html

No changes compared to the previous version.

[fix] (ABC-1066): Fix autofocus on search box in filter menu popover

---

src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js

**Scheduler**
- Fixed scheduler calendar header overflowing on very small screens.

[fix] (ABC-1067): Fix responsive in scheduler calendar on small screens

---

src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenuGroup/__tests__/filterMenuGroup.test.js
src/modules/base/filterMenuGroup/filterMenuGroup.js

- Add focusSearchInput() method.
**Filter Menu Group**
- Add focusSearchInput() method.

[feat] (ABC-1068): Add focusSearchInput method to filter menu

---

jest-mock/components/base/datatable/datatable.js
src/modules/base/datatable/datatable.js

**Data Table**
- Added `focusRow()` method.

Feature abc 1069 add focus row method to data table

---

src/modules/base/chipContainer/__tests__/chipContainer.test.js
src/modules/base/chipContainer/chipContainer.html
src/modules/base/chipContainer/chipContainer.js

**Chip Container**
- Improved the number of visible and collapsed items depending on the available space

[fix] (ABC-1074): Chip Container - Raise the margin limit for displaying '+ more'

---

package-lock.json
src/modules/base/datatable/datatable.js
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/scheduler.css
src/modules/base/scheduler/scheduler.html
src/modules/base/scheduler/scheduler.js

**Scheduler**
- Allowed the scheduler to be smaller than 100% of the view height.
- In the horizontal timeline display, synchronized the vertical scrolling of the resources and the schedule.

[feat] (ABC-1073): Allow the scheduler to be smaller than 100vh

---

src/modules/base/primitiveSchedulerAgenda/__tests__/primitiveSchedulerAgenda.test.js
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.html
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/__tests__/primitiveSchedulerCalendar.test.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/schedulerUtils/eventData.js
src/modules/base/schedulerUtils/scheduleBase.js
src/modules/base/utilsPrivate/dateTimeUtils.js
src/modules/base/utilsPrivate/utilsPrivate.js

**Scheduler**
- Added chips in the side panel calendar, on the dates that contain events.

[feat] (ABC-1020): Mark the dates with events in the scheduler side panel calendar

---

src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js

**Datatable**
- Fix blur when primitive cell

[fix](ABC-1080): Datatable - Fix blur when primitive cell

---

src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.css
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js

**Scheduler**
- Fixed the automatic resizing of the sheduler cells, when the display is calendar and the time span is a month.

[fix] (ABC-1083): Fix vertical resizing of monthly calendar in scheduler

---

src/modules/base/datatable/datatable.js
src/modules/base/primitiveCellAvatar/primitiveCellAvatar.html
src/modules/base/primitiveCellAvatar/primitiveCellAvatar.js
src/modules/base/primitiveCellAvatarGroup/primitiveCellAvatarGroup.html
src/modules/base/primitiveCellAvatarGroup/primitiveCellAvatarGroup.js
src/modules/base/primitiveCellBadge/primitiveCellBadge.js
src/modules/base/primitiveCellCheckboxButton/primitiveCellCheckboxButton.html
src/modules/base/primitiveCellCheckboxButton/primitiveCellCheckboxButton.js
src/modules/base/primitiveCellColorPicker/primitiveCellColorPicker.html
src/modules/base/primitiveCellColorPicker/primitiveCellColorPicker.js
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.html
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveCellCounter/primitiveCellCounter.html
src/modules/base/primitiveCellCounter/primitiveCellCounter.js
src/modules/base/primitiveCellDateRange/primitiveCellDateRange.html
src/modules/base/primitiveCellDateRange/primitiveCellDateRange.js
src/modules/base/primitiveCellLookup/primitiveCellLookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.js
src/modules/base/primitiveCellRichText/primitiveCellRichText.html
src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.html
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js
src/modules/base/primitiveCellUtils/primitiveCellUtils.js
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js

**Datatable**
- Panel open above the cell when not enough space below

[Fix] (ABC-1086): Datatable - Panel open above the cell when not enough space below

---

src/modules/base/datatable/__docs__/datatable.stories.js
src/modules/base/datatable/__examples__/datatable.js
src/modules/base/datatable/datatable.js
src/modules/base/datatable/lookup.html
src/modules/base/datatable/richText.html
src/modules/base/datatable/textarea.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.js
src/modules/base/primitiveCellRichText/primitiveCellRichText.html
src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.html
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js
src/modules/base/storybookWrappers/datatable/datatable.html
src/modules/base/storybookWrappers/datatable/datatable.js

**Datatable**
- Fixed wrapTextMaxLines for textArea, RichText and Lookup

[fix](ABC-1087): Datatable - Fixed wrapTextMaxLines for textArea, RichText and Lookup

---

jest-mock/components/base/inputDateRange/inputDateRange.js
jest-mock/components/base/positionLibrary/positionLibrary.js
jest.config.js
src/modules/base/inputDateRange/__tests__/inputDateRange.test.js
src/modules/base/inputDateRange/inputDateRange.html
src/modules/base/inputDateRange/inputDateRange.js
src/modules/base/positionLibrary/util.js

- Updated the date pickers popovers so they are placed automatically and avoid overflowing the screen.

[feat] (ABC-1088): Position the input date range popovers automatically

---

src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js

No changes compared to last package version.

[fix] (ABC-1092): Save data table draft percent on edit popover blur

---

src/modules/base/datatable/datatable.js

**Data Table**
- Added resize column method

[feat](ABC-1093): Data Table - Added resize column method

---

src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputToggle/inputToggle.js

- Fixed issue with line clamp styling hook

[fix](ABC-1095): Input Choice Set - Fix issue with line clamp

---

src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js

**Data Table**
- Fixed the removal of a value in a combobox type column.

[fix] (ABC-1096): Allow removal of a combobox value in data table

---

src/modules/base/datatable/datatable.js
src/modules/base/positionLibrary/positionLibrary.js
src/modules/base/profileCard/__docs__/profileCard.jsdoc.js
src/modules/base/profileCard/profileCard.css

[Fix](ABC-1100): Profile Card - Border color should be the same as the card component

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.css
src/modules/base/list/list.js

**List **
- Border color darker only when sortable

[fix](ABC-1103): List - Border color darker only when sortable

---

src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/__tests__/primitiveSchedulerCalendar.test.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerEventOccurrence/eventOccurrence.css
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/primitiveSchedulerTimeline/__tests__/primitiveSchedulerTimeline.test.js
src/modules/base/scheduler/__docs__/data.js
src/modules/base/scheduler/__docs__/scheduler.jsdoc.js
src/modules/base/scheduler/__examples__/agenda/agenda.js
src/modules/base/scheduler/__examples__/availableAndDisabledTimes/availableAndDisabledTimes.js
src/modules/base/scheduler/__examples__/calendar/calendar.js
src/modules/base/scheduler/__examples__/labels/labels.js
src/modules/base/scheduler/__examples__/readOnly/readOnly.js
src/modules/base/scheduler/__examples__/verticalTimeline/verticalTimeline.js
src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/dateComputations.js
src/modules/base/schedulerUtils/event.js
src/modules/base/schedulerUtils/eventData.js
src/modules/base/schedulerUtils/scheduleBase.js

No changes compared to previous release.

[fix] (ABC-1104): Fix scheduler event min size and timezone management

---

src/modules/base/primitiveCellLookup/primitiveCellLookup.js

No changes compared to previous release.

[fix] (ABC-1107): Auto close data table lookup cell after change

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__examples__/activityTimeline.js
src/modules/base/activityTimeline/__examples__/infiniteLoadingActivityTimeline.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.js
src/modules/base/storybookWrappers/activityTimeline/infiniteLoadingActivityTimeline.js

- Added the `locale` attribute.

[feat] (ABC-1110): Add locale attribute to activity timeline

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.md
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__examples__/toggleStretch/toggleStretch.html
src/modules/base/inputChoiceSet/__examples__/toggleStretch/toggleStretch.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added type attribute stretch to toggle variant
- Fixed button border color
- Fix button label on multi-line

[fix](ABC-1108): Input Choice Set - Fix button issues and added toggle stretch

---

src/modules/base/dualListbox/__docs__/dualListbox.stories.js
src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js
src/modules/base/dualListbox/option.js

- Added `search` event.
- Added `search` attribute.

[feat] (ABC-1113): Add search event and function to dual listbox

---

src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/__examples__/base.js
src/modules/base/avatarGroup/__examples__/infiniteLoading.js
src/modules/base/avatarGroup/__examples__/infiniteLoading/infiniteLoading.html
src/modules/base/avatarGroup/__examples__/infiniteLoading/infiniteLoading.js
src/modules/base/avatarGroup/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/avatarGroup/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.html
src/modules/base/avatarGroup/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.js
src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/storybookWrappers/avatarGroup/infiniteLoading.html
src/modules/base/storybookWrappers/avatarGroup/infiniteLoading.js
src/modules/base/storybookWrappers/avatarGroup/infiniteLoadingUsingShowMore.html
src/modules/base/storybookWrappers/avatarGroup/infiniteLoadingUsingShowMore.js

- Added `enable-infinite-loading`, `load-more-offset` and `is-loading` attributes.
- Added `loadmore` and `itemsvisibilitytoggle` events.

[feat] (ABC-1115): Add infinite loading to avatar group

---

src/modules/base/avatarGroup/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.js
src/modules/base/storybookWrappers/avatarGroup/infiniteLoadingUsingShowMore.js
src/modules/base/storybookWrappers/verticalVisualPicker/infiniteLoading.html
src/modules/base/storybookWrappers/verticalVisualPicker/infiniteLoading.js
src/modules/base/storybookWrappers/verticalVisualPicker/infiniteLoadingUsingShowMore.html
src/modules/base/storybookWrappers/verticalVisualPicker/infiniteLoadingUsingShowMore.js
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.stories.js
src/modules/base/verticalVisualPicker/__examples__/infiniteLoading.js
src/modules/base/verticalVisualPicker/__examples__/infiniteLoading/infiniteLoading.html
src/modules/base/verticalVisualPicker/__examples__/infiniteLoading/infiniteLoading.js
src/modules/base/verticalVisualPicker/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/verticalVisualPicker/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.html
src/modules/base/verticalVisualPicker/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.js
src/modules/base/verticalVisualPicker/__examples__/subItems/subItems.html
src/modules/base/verticalVisualPicker/__tests__/verticalVisualPicker.test.js
src/modules/base/verticalVisualPicker/item.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.js

- Added `enable-infinite-loading`, `is-loading`, `load-more-offset` and `max-count` attributes.
- Added `loadmore` and `itemsvisibilitytoggle` events.

[feat] (ABC-1119): Add infinite loading to vertical visual picker

---

src/modules/base/inputChoiceSet/inputChoiceSet.js

- Init orientation attributes when setting orientation

[fix](ABC-1122): Input Choice Set - Init orientation attributes when setting orientation

---

jest-mock/components/base/resizeObserver/resizeObserver.js
src/modules/base/layout/__tests__/layout.test.js
src/modules/base/layout/layout.js

[feat] (ABC-1123): Allow resize observer centralization in layout parent

---

src/modules/base/primitiveCellCombobox/primitiveCellCombobox.html
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js

**Data Table**
- Improved support of multi-select combobox columns in Salesforce's platform.

[fix] (ABC-1124): Improve support of multi select combobox in data table

---

src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/dateTimePicker/dateTimePicker.js

[feat] (ABC-1127): Add navigate event to date time picker

---

jest-mock/components/base/layout/layout.html
jest-mock/components/base/layout/layout.js
jest-mock/components/base/layoutItem/layoutItem.html
jest-mock/components/base/layoutItem/layoutItem.js
jest.config.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/layout/layout.html
src/modules/base/layoutItem/layoutItem.js
src/modules/base/list/__examples__/baseWithInfiniteLoading/baseWithInfiniteLoading.html
src/modules/base/list/__examples__/baseWithInfiniteLoading/baseWithInfiniteLoading.js
src/modules/base/list/__examples__/columnsWithInfiniteLoading/columnsWithInfiniteLoading.html
src/modules/base/list/__examples__/columnsWithInfiniteLoading/columnsWithInfiniteLoading.js
src/modules/base/list/__examples__/singleLineWithInfiniteLoading/singleLineWithInfiniteLoading.html
src/modules/base/list/__examples__/singleLineWithInfiniteLoading/singleLineWithInfiniteLoading.js
src/modules/base/list/__tests__/data.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/item.js
src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js
src/modules/base/storybookWrappers/list/infiniteGrid.html
src/modules/base/storybookWrappers/list/infiniteGrid.js

**List**
- Added `previousIndex` and `newIndex` keys to the `reorder` event.
**List**
- Fixed `loadmore` event dispatch timing in single line variant.
- Improved performance of the list.

[feat] (ABC-1120): Improve infinite loading in single line lists

---

src/modules/base/progressCircle/__docs__/progressCircle.jsdoc.js
src/modules/base/progressCircle/progressCircle.css
src/modules/base/separator/__docs__/separator.jsdoc.js
src/modules/base/separator/separator.css

**Progress Circle**
- Add title styling hooks
- `--avonni-progress-circle-title-font-family`
- `--avonni-progress-circle-title-font-size`
- `--avonni-progress-circle-title-line-height`
- `--avonni-progress-circle-title-letter-spacing`
**Separator**
- Add label styling hooks
- `--avonni-separator-label-font-family`
- `--avonni-separator-label-line-height`
- `--avonni-separator-label-letter-spacing`

[feat](FSC-1125): Add missing styling hooks for experience styles

---

src/modules/base/list/__docs__/data.js
src/modules/base/list/__examples__/columnsWithImageBottom/columnsWithImageBottom.js
src/modules/base/list/__examples__/columnsWithImageOverlay/columnsWithImageOverlay.js
src/modules/base/list/__examples__/columnsWithInfiniteLoading/columnsWithInfiniteLoading.js
src/modules/base/list/__examples__/images/images.js
src/modules/base/list/__examples__/singleLineWithInfiniteLoading/singleLineWithInfiniteLoading.js
src/modules/base/list/__examples__/sortableWithImagesAndAvatars/sortableWithImagesAndAvatars.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html

**List**
- Removed the empty link from the infos with no link set.

[fix] (ABC-1131): Allow list info without a link

---

jest-mock/components/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
jest-mock/components/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
jest-mock/components/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/primitiveSchedulerAgenda/__tests__/primitiveSchedulerAgenda.test.js
src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.html
src/modules/base/primitiveSchedulerCalendar/__tests__/primitiveSchedulerCalendar.test.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceBase.test.js
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/primitiveSchedulerTimeline/__tests__/primitiveSchedulerTimeline.test.js
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.html
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/scheduler/__docs__/scheduler.stories.js
src/modules/base/scheduler/__examples__/scheduler.js
src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/defaults.js
src/modules/base/scheduler/scheduler.html
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/defaults.js
src/modules/base/schedulerUtils/scheduleBase.js
src/modules/base/schedulerUtils/schedulerUtils.js
src/modules/base/storybookWrappers/scheduler/scheduler.html
src/modules/base/storybookWrappers/scheduler/scheduler.js

**Scheduler**
- Added `hidden-actions` attribute.

[feat] (ABC-1132): Add hidden actions to scheduler

---

src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js

**Data Table**
- Fixed wraptext for textArea and RichText

[fix](ABC-1133): Data Table - Fixed wraptext for textArea and RichText

---

src/modules/base/datatable/combobox.html
src/modules/base/datatable/datatable.js
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.html
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js

**Data Table**
- Combobox can be wrappable when not mulitiselect

[feat](ABC-1134): Data Table - Combobox can be wrappable when not mulitiselect

---

src/modules/base/dualListbox/__docs__/dualListbox.stories.js
src/modules/base/dualListbox/dualListbox.js
src/modules/base/verticalVisualPicker/__docs__/data.js
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.stories.js
src/modules/base/verticalVisualPicker/__examples__/maximumAndMinimum/maximumAndMinimum.html
src/modules/base/verticalVisualPicker/__examples__/maximumAndMinimum/maximumAndMinimum.js
src/modules/base/verticalVisualPicker/__examples__/verticalVisualPicker.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.js
src/modules/base/visualPicker/__docs__/visualPicker.stories.js
src/modules/base/visualPicker/__examples__/maximumAndMinimum/maximumAndMinimum.html
src/modules/base/visualPicker/__examples__/maximumAndMinimum/maximumAndMinimum.js
src/modules/base/visualPicker/__examples__/visualPicker.js
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Add `min` attribute
- Add `max` attribute
- Add `messageWhenRangeOverflow` attribute
- Add `messageWhenRangeUnderflow` attribute
- Add `min` attribute
- Add `max` attribute
- Add `messageWhenRangeOverflow` attribute
- Add `messageWhenRangeUnderflow` attribute

[Feat](ABC-1135): Visual Picker - Add min and max attributes

---

src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/primitiveSchedulerHeaderGroup/primitiveSchedulerHeaderGroup.js

No changes compared to the previous version.

[fix] (ABC-1136): Prevent error in scheduler when used in salesforce

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/storybookWrappers/activityTimeline/infiniteLoadingUsingShowMore.html
src/modules/base/storybookWrappers/activityTimeline/infiniteLoadingUsingShowMore.js

- Added `itemsvisibilitytoggle` event.

[feat] (ABC-1116): Add itemsvisibilitytoggle event to activity timeline

---

src/modules/base/primitiveProgressStep/__tests__/primitiveProgressStep.test.js
src/modules/base/primitiveProgressStep/primitiveProgressStep.css
src/modules/base/primitiveProgressStep/primitiveProgressStep.html
src/modules/base/primitiveProgressStep/primitiveProgressStep.js
src/modules/base/progressIndicator/__tests__/progressIndicator.test.js
src/modules/base/progressIndicator/progressIndicator.html
src/modules/base/progressIndicator/progressIndicator.js
src/modules/base/progressIndicator/step.js

**Progress Indicator**
- Added styling hooks to allow customization of the steps icons.

[feat] (ABC-1142): Add styling hooks to progress indicator icons

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__examples__/daily/daily.html
src/modules/base/activityTimeline/__examples__/daily/daily.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js

- Added option to group by "Day"

[Feat] (ABC-1148): Timeline - Add group by option "Day"

---

src/modules/base/filterMenu/__docs__/filterMenu.jsdoc.js
src/modules/base/filterMenu/filterMenuVertical.css
src/modules/base/filterMenu/filterMenuVertical.html
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added styling hooks for the vertical variant.
- Added styling hooks for the options label and checkboxes.

[feat] (ABC-1147): Add styling hooks to filter menu and input choice set

---

src/modules/base/avatarGroup/avatarGroup.js

[Fix](ABC-1149): Avatar Group - Max count never taken in account

---

jest-mock/components/base/combobox/combobox.js
jest-mock/components/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/combobox/__docs__/combobox.stories.js
src/modules/base/combobox/__examples__/combobox.js
src/modules/base/combobox/__examples__/infiniteLoadingCombobox.js
src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js
src/modules/base/dualListbox/dualListbox.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/action.js
src/modules/base/primitiveCombobox/option.js
src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/storybookWrappers/combobox/combobox.html
src/modules/base/storybookWrappers/combobox/combobox.js

**Combobox**
- Added min and max
- Added messageWhenRangeOverflow and messageWhenRangeUnderflow

[Feat](ABC-1152): Combobox - Add min, max, messageWhenRangeOverflow and messageWhenRangeUnderflow

---

src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html

- Added Show more button Styling hooks

[feat](ABC-1154): Vertical Visual Picker - Added show more button styling hook

---

src/modules/base/metric/__docs__/metric.stories.js
src/modules/base/metric/__examples__/metric.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js
src/modules/base/primitiveMetric/__tests__/primitiveMetric.test.js
src/modules/base/primitiveMetric/primitiveMetric.css
src/modules/base/primitiveMetric/primitiveMetric.html
src/modules/base/primitiveMetric/primitiveMetric.js

**Metric**
- Added `value-is-loading` and `secondary-value-is-loading` attributes.

[feat] (ABC-1155): Add value and secondary value loading to metric

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/verticalActivityTimeline.css
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html

- Added styling hooks to show more button neutral

[Feat](ABC-1154): Activity Timeline - Add styling hooks to show more button neutral

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/verticalActivityTimeline.css
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/alert/__docs__/alert.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/verticalVisualPicker/verticalVisualPicker.html

- Infinite loading displayed twice when max count

[Fix](ABC-1158): Avatar Group - Infinite loading displayed twice when max count

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__docs__/data.js
src/modules/base/activityTimeline/__examples__/activityTimeline.js
src/modules/base/activityTimeline/__examples__/endDate/endDate.html
src/modules/base/activityTimeline/__examples__/endDate/endDate.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/__tests__/horizontalActivityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.js

- Added `endDate` field to horizontal timeline item
- Added `intervalDaysLength` attribute to customize the default range

[Feat](ABC-1156): Activity Timeline - Horizontal - Add endDate field and add option to customize the default range

---

src/modules/base/progressBar/__docs__/progressBar.jsdoc.js
src/modules/base/progressBar/progressBar.css
src/modules/base/progressBar/progressBar.html
src/modules/base/progressBar/progressBarVertical.css
src/modules/base/progressBar/progressBarVertical.html

- Added label line clamp styling hook
- `--avonni-progress-bar-label-line-clamp`

[Feat](ABC-1157): Progress Bar - Truncate the label

---

src/modules/base/avatarGroup/avatarGroup.js

No changes compared to previous version

[fix] (ABC-1162): Fix useless loadmore and double loader in avatar group

---

src/modules/base/list/list.css
src/modules/base/list/list.html

**List**
- Fixed the alignment of the actions, when the list is in a popover.

[fix] (ABC-1163): Fix list action alignment in popovers

---

src/modules/base/buttonMenu/buttonMenu.html
src/modules/base/buttonMenu/buttonMenu.js

[feat](ABC-1114): Button Menu - Changed iconSrc position

---

src/modules/base/progressBar/progressBar.css
src/modules/base/progressBar/progressBarVertical.css

- Added gradient option for background

[feat](ABC-1165): Progress Bar - Add Gradient option for background

---

src/modules/base/combobox/__docs__/combobox.jsdoc.js
src/modules/base/primitiveCombobox/primitiveCombobox.css
src/modules/base/primitiveCombobox/primitiveCombobox.html
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.css
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.html

**Combobox**
- Added styling new hooks

[Feat](ABC-1159): Combobox - Add styling new hooks

---

src/modules/base/datatable/datatable.js
src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveCellDateRange/primitiveCellDateRange.js
src/modules/base/primitiveCellLookup/primitiveCellLookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.js

**Data Table**
-  Bug when massEdit lookup field

[Fix](ABC-1164): Data table - Bug when massEdit lookup field

---

src/modules/base/list/list.js

**List**
- Fixed the update of `actions` after the component has been inserted into the DOM.

[fix] (ABC-1167): Fix update of list actions after connexion

---

src/modules/base/progressBar/__tests__/progressBar.test.js
src/modules/base/progressBar/progressBar.html
src/modules/base/progressBar/progressBar.js
src/modules/base/progressBar/progressBarVertical.css
src/modules/base/progressBar/progressBarVertical.html

- Improved gradient calculation based on the progress bar value

[Feat](ABC-1169): Progress Bar - Calculate gradient based on the value

---

src/modules/base/button/button.js
src/modules/base/buttonMenu/__docs__/buttonMenu.jsdoc.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.css
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/primitiveButton/primitiveButton.js

- Add `stretch` attribute
- Add `--avonni-button-menu-dropdown-max-width` styling hook

[Feat](ABC-1168): Button Menu - Add stretch attribute

---

src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/list.html
src/modules/base/list/list.js

[fix] (ABC-1175): Fix list drag and drop error

---

src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/__tests__/visualPickerLink.test.js
src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.html
src/modules/base/visualPickerLink/visualPickerLink.js
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.css
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.html

- Added styling hooks to customize the border between avatar and content

[Feat](ABC-1173): Visual Picker Link - Add styling hooks to customize the border between avatar and content

---

src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js
src/modules/base/primitiveCellLookup/primitiveCellLookup.js
src/modules/base/primitiveCellNameLookup/primitiveCellNameLookup.js
src/modules/base/primitiveCellRichText/primitiveCellRichText.js
src/modules/base/primitiveCellTextarea/primitiveCellTextarea.js

**Data Table**
- Fixed wrapped issue for textarea, combobox, richtext, lookup and lookupName

[fix](ABC-1176): Data Table - Fixed wrapped issue

---

src/modules/base/datatable/__docs__/datatable.stories.js
src/modules/base/datatable/__examples__/datatable.js
src/modules/base/datatable/datatable.js
src/modules/base/storybookWrappers/datatable/datatable.html
src/modules/base/storybookWrappers/datatable/datatable.js

**Data Table**
- Added Wrap Table Header

[feat](ABC-1178): Data Table - Added Wrap Table Header

---

src/modules/base/filterMenu/__docs__/filterMenu.jsdoc.js
src/modules/base/filterMenu/__docs__/filterMenu.stories.js
src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.html
src/modules/base/filterMenu/item.js
src/modules/base/filterMenuGroup/__docs__/data.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js
src/modules/base/layoutItem/__tests__/layoutItem.test.js
src/modules/base/storybookWrappers/filterMenu/infiniteLoading.js

- Added the `color` key to the items.
- Added the `color` key to the options.

[feat] (ABC-1075): Add color to filter menu and input choice set items

---

lwc.config.json
src/modules/base/datatable/datatable.js
src/modules/base/datatable/lookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.html
src/modules/base/primitiveCellLookup/primitiveCellLookup.js
src/modules/base/primitiveDatatableIeditInputWrapperCustom/primitiveDatatableIeditInputWrapperCustom.html
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.html
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/combobox.html
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/lookup.html
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/nameLookup.html
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/primitiveDatatableIeditTypeFactoryCustom.js
src/modules/base/recordPicker/recordPicker.html
src/modules/base/recordPicker/recordPicker.js
src/modules/base/recordPicker/recordPicker.js-meta.xml

**Data Table**
- Added typeAttribute relationshipFieldName to lookup type

[feat](ABC-1184): Data Table - Added typeAttribute relationshipFieldName to lookup type

---

src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/dateTimePicker/dateTimePicker.js

- Added `actions` slot
- Moved the Time Zone input under the date
- Changed the appearance of the time slot buttons
- Changed the appearance of the toolbar

[feat](ABC-1183): Date Time Picker - Refactor the UI

---

src/modules/base/primitiveDropdownMenu/__tests__/primitiveDropdownMenu.test.js
src/modules/base/primitiveDropdownMenu/primitiveDropdownMenu.html
src/modules/base/primitiveDropdownMenu/primitiveDropdownMenu.js

[fix] (ABC-1186): Focus primitive dropdown menu on render

---

src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/dateTimePicker/dateTimePicker.html

[fix](ABC-1187): Date Time Picker - Overflow not working when a size is set in the style

---

src/modules/base/button/button.css
src/modules/base/buttonMenu/buttonMenu.css

- Fixed css and styling hooks for tokens and themes

[fix](ABC-1190): Button Menu - Fixed css and styling hooks for tokens and themes

---

src/modules/base/colorPicker/colorPicker.js
src/modules/base/colorPicker/inline.html
src/modules/base/colorPicker/standard.html

- Fixed ability to use menu-variant when no menu-icon-name

[Fix](ABC-1191): Color Picker - Fixed menu variant

---

src/modules/base/buttonMenu/buttonMenu.css

[feat] (ABC-1196): Allow button menu height to grow

---

src/modules/base/colorPicker/colorPicker.js
src/modules/base/colorPicker/standard.html
src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.js

**Slider**
- Added gradient option for background.

[Feat](ABC-1194): Slider - Add Gradient option for background

---

src/modules/base/blockquote/blockquote.css
src/modules/base/buttonIcon/buttonIcon.css
src/modules/base/calendar/calendar.css
src/modules/base/card/card.css
src/modules/base/carousel/carousel.css
src/modules/base/chip/__docs__/chip.jsdoc.js
src/modules/base/chip/chip.css
src/modules/base/colorGradient/colorGradient.css
src/modules/base/colorPicker/shared.css
src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/dualListbox/dualListbox.css
src/modules/base/dynamicMenu/dynamicMenu.css
src/modules/base/heroBanner/heroBanner.css
src/modules/base/iconPicker/iconPicker.css
src/modules/base/illustration/illustration.css
src/modules/base/image/__docs__/image.jsdoc.js
src/modules/base/image/image.css
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputDateRange/inputDateRange.css
src/modules/base/list/list.css
src/modules/base/metric/metric.css
src/modules/base/pagination/pagination.css
src/modules/base/path/path.css
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
src/modules/base/primitiveCombobox/primitiveCombobox.css
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.css
src/modules/base/primitivePill/primitivePill.css
src/modules/base/primitiveTreeItem/primitiveTreeItem.css
src/modules/base/slider/slider.css

**Components**
-  Review colors when using a custom theme branding

[Fix](ABC-1198) Components - Review colors when using a custom theme branding

---

src/modules/base/datatable/__docs__/data.js
src/modules/base/datatable/inlineEdit.js
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.css
src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/primitiveDatatableIeditTypeFactoryCustom.js
src/modules/base/primitiveDatatableIeditTypeFactoryCustom/richText.html

**Data Table**
- Bigger edit panel for textarea and richText

[feat](ABC-1189): Data Table - Bigger edit panel for textarea and richText

---

src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.css
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/activityTimeline/horizontalActivityTimeline.js

- In the horizontal orientation:
- Fixed overflow issue for item popover.
- Fixed an issue with vertical scrolling sometimes causing horizontal scrolling to trigger.

[Fix](ABC-1197): Horizontal Timeline - Overflow issue

---

src/modules/base/avatar/__tests__/avatar.test.js
src/modules/base/avatar/avatar.html
src/modules/base/avatar/avatar.js
src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/primitiveAvatar/__tests__/primitiveAvatar.test.js
src/modules/base/primitiveAvatar/primitiveAvatar.css
src/modules/base/primitiveAvatar/primitiveAvatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.js

**Avatar**
- Add `href` attribute
- Add `item.href` attribute

[Feat](ABC-1200): Global - Add href attribute

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.css
src/modules/base/slider/slider.js

**Slider**
- Fixed the position of custom labels

[Fix](ABC-1205): Slider - Fix position issue for Custom Labels

---

src/modules/base/datatable/datatable.js

**Data Table**
- Added method to update the checkbox column

[feat](ABC-1209): Data Table - Added method to update the checkbox column

---

src/modules/base/datatable/datatable.js

**Data Table**
- Add `oneditbuttonclickcustom` event.

[Feat](ABC-1208): Data Table - Remove event.stopPropagation for "editbuttonclickcustom"

---

src/modules/base/buttonIconPopover/buttonIconPopover.js
src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/buttonMenu/__examples__/buttonMenuBase.js
src/modules/base/buttonMenu/__examples__/buttonMenuIllustration.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.css
src/modules/base/buttonMenu/buttonMenu.html
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/buttonPopover/buttonPopover.html
src/modules/base/buttonPopover/buttonPopover.js
src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
src/modules/base/storybookWrappers/buttonMenu/base.html
src/modules/base/storybookWrappers/buttonMenu/base.js
src/modules/base/storybookWrappers/buttonMenu/illustration.html
src/modules/base/storybookWrappers/buttonMenu/illustration.js
src/modules/base/storybookWrappers/submenu/leftAlignment.html
src/modules/base/storybookWrappers/submenu/leftAlignment.js
src/modules/base/submenu/__docs__/submenu.stories.js
src/modules/base/submenu/__examples__/leftAlignment.js
src/modules/base/submenu/__examples__/leftAlignment/leftAlignment.html
src/modules/base/submenu/__examples__/leftAlignment/leftAlignment.js
src/modules/base/submenu/__examples__/submenu.js
src/modules/base/submenu/submenu.css
src/modules/base/submenu/submenu.html
src/modules/base/submenu/submenu.js

[Feat](FSC-1207): Button Menu - Add trigger attribute

---

src/modules/base/progressBar/__docs__/progressBar.stories.js
src/modules/base/progressBar/__examples__/progressBar.js
src/modules/base/progressBar/__tests__/progressBar.test.js
src/modules/base/progressBar/progressBar.html
src/modules/base/progressBar/progressBar.js
src/modules/base/progressBar/progressBarVertical.html

- Added `is-loading` attribute.

[feat] (ABC-1212): Add is-loading attribute to progress bar

---

src/modules/base/list/list.js

**List**
- Display shadow for the last item for the card divider.

[feat](ABC-1213): List - Show shadow for the last item for card divider

---

src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js

- Improve icon overflow for stack and grid layouts.

[Feat](ABC-1215): Avatar Group - Overflow icon exceeds components limits

---

src/modules/base/list/list.js

[fix] (ABC-1217): Prevent list rerender when the same actions are passed

---

src/modules/base/button/button.css
src/modules/base/buttonIcon/buttonIcon.css
src/modules/base/buttonMenu/buttonMenu.css

**Button, Button Menu, Button Icon**
- missing background on hover and active

[fix](ABC-1216): Buttons - Fixed missing background on hover and active

---

src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceAgenda.test.js
src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceCalendar.test.js
src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceTimeline.test.js
src/modules/base/primitiveSchedulerEventOccurrence/eventOccurrence.css
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js

**Scheduler**
- Added styling hooks for events' labels.

[feat] (ABC-1218): Add styling hooks to scheduler event labels

---

src/modules/base/button/__docs__/button.jsdoc.js
src/modules/base/button/button.css
src/modules/base/buttonMenu/__docs__/buttonMenu.jsdoc.js
src/modules/base/buttonMenu/buttonMenu.css

**Button**
- Add `--avonni-button-horizontal-alignment` styling hook
- Add `--avonni-button-menu-horizontal-alignment` styling hook

[feat](ABC-1221): Button - Add horizontal alignment for stretched

---

src/modules/base/positionLibrary/overlayDetector.js
src/modules/base/positionLibrary/positionLibrary.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Data table**
- Fixed overflow issue with combobox

[fix](ABC-1224): Data table - Fixed overflow issue with combobox

---

src/modules/base/expandableSection/__docs__/expandableSection.jsdoc.js
src/modules/base/expandableSection/expandableSection.css

- Add vertical spacing styling hooks for the content
- `--avonni-expandable-section-content-spacing-block-start`
- `--avonni-expandable-section-content-spacing-block-end`

[Feat](ABC-1223): Expandable Section - Add content vertical spacing styling hooks

---

src/modules/base/storybookWrappers/visualPicker/infiniteLoading.html
src/modules/base/storybookWrappers/visualPicker/infiniteLoading.js
src/modules/base/storybookWrappers/visualPicker/infiniteLoadingUsingShowMore.html
src/modules/base/storybookWrappers/visualPicker/infiniteLoadingUsingShowMore.js
src/modules/base/visualPicker/__docs__/visualPicker.stories.js
src/modules/base/visualPicker/__examples__/infiniteLoading.js
src/modules/base/visualPicker/__examples__/infiniteLoading/infiniteLoading.html
src/modules/base/visualPicker/__examples__/infiniteLoading/infiniteLoading.js
src/modules/base/visualPicker/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/visualPicker/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.html
src/modules/base/visualPicker/__examples__/infiniteLoadingUsingShowMore/infiniteLoadingUsingShowMore.js
src/modules/base/visualPicker/__examples__/visualPicker.js
src/modules/base/visualPicker/__tests__/visualPicker.test.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Added `enable-infinite-loading`, `is-loading`, `load-more-offset` and `max-count` attributes.
- Added `loadmore` and `itemsvisibilitytoggle` events.

[Feat](ABC-1225): Visual Picker - Add infinite loading

---

src/modules/base/list/__docs__/data.js
src/modules/base/list/__docs__/list.jsdoc.js
src/modules/base/list/__docs__/list.stories.js
src/modules/base/list/__examples__/checkList/checkList.html
src/modules/base/list/__examples__/checkList/checkList.js
src/modules/base/list/__examples__/list.js
src/modules/base/list/__tests__/data.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/item.js
src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js

**Check List**
- Added `check-list` variant.
- Added `strikeThroughOnCheck` attribute.
- Added `itemcheck` event.
- Added styling hooks for checkbox
- `--avonni-list-item-checkbox-button-size`
- `--avonni-list-item-checkbox-button-sizing-border`
- `--avonni-list-item-checkbox-button-radius-border`
- `--avonni-list-item-checkbox-button-color-border`
- `--avonni-list-item-checkbox-button-color-background`
- `--avonni-list-item-checkbox-button-color-background-active`
- `--avonni-list-item-checkbox-button-icon-color-background`

[Feat](ABC-1226): List - Add new variant Check List

---

src/modules/base/card/card.js

[feat] (ABC-1229): Allow refresh of card slots after 1st render

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

**Input Choice set**
- Fixed Perfomance issue

[fix](ABC-1222): Input Choice Set - Fixed perfomance issue

---

src/modules/base/expandableSection/__docs__/expandableSection.jsdoc.js
src/modules/base/expandableSection/expandableSection.css
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

**Expandable section**
- Add color border styling hooks

[Feat](ABC-1228): Expandable section - Add color border styling hooks

---

src/modules/base/slider/slider.css
src/modules/base/slider/slider.html

**Slider**
- Fix Salesforce Experience style issue with `slds-form-element` class

[fix](ABC-1233): Slider - Make sure no margin bottom is added to slds-form-element class

---

src/modules/base/filterMenu/filterMenuVertical.css
src/modules/base/filterMenu/filterMenuVertical.html

- Fix Salesforce Experience style conflict with slds-form-element_legend class

[fix](ABC-1234): Filter menu - Make sure no margin-bottom is added to slds-form-element_legend class

---

src/modules/base/verticalVisualPicker/__tests__/verticalVisualPicker.test.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.html
src/modules/base/verticalVisualPicker/verticalVisualPicker.js
src/modules/base/visualPicker/__tests__/visualPicker.test.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Add itemclick event
- Add itemclick event
- Fix unwanted scrollbar appearing

[Feat](ABC-1232): Visual Pickers - Add itemclick event

---

src/modules/base/list/list.css
src/modules/base/list/list.html

**List**
- Fix unwanted scrollbar
- Make sure component takes full width and height

[Fix](ABC-1236): List - Unwanted scrollbar appearing

---

src/modules/base/dateTimePicker/dateTimePicker.js

- Avoid timezone change event bubbling out of the component.

[fix](ABC-1240): Date Time Picker - Timezone change event bubbling out

---

src/modules/base/primitiveProgressStep/primitiveProgressStep.css
src/modules/base/primitiveProgressStep/primitiveProgressStep.html
src/modules/base/primitiveProgressStep/primitiveProgressStep.js

**Progress Popover**
- Fixed alignment issue of step icons.

[Fix](ABC-1239): Progress Popover - Misalignment issues

---

src/modules/base/dialog/__docs__/dialog.stories.js
src/modules/base/dialog/__examples__/dialog.js
src/modules/base/dialog/__tests__/dialog.test.js
src/modules/base/dialog/dialog.html
src/modules/base/dialog/dialog.js
src/modules/base/storybookWrappers/dialog/dialog.html
src/modules/base/storybookWrappers/dialog/dialog.js

**Dialog**
- Improved accessibility, partly by adding attributes (`aria-described-by`, `aria-labelled-by` and `close-button-alternative-text`) and `focus` method.

[feat] (ABC-1238): Improve dialog use and accessibility

---

src/modules/base/inputPen/inputPen.css
src/modules/base/inputPen/inputPen.html
src/modules/base/inputPen/inputPen.js
src/modules/base/inputPen/smoothToolManager.js
src/modules/base/inputPen/straightToolManager.js
src/modules/base/inputPen/toolManager.js

[Fix](ABC-1241): Input Pen - Refactoring

---

src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.css
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.html

- Added line clamp styling hooks for the figure title.
- `--avonni-visual-picker-title-line-clamp`

[Feat](ABC-1242): Visual Picker - Add line clamp styling hooks for Figure Title

---

src/modules/base/iconPicker/icons/salesforceIcons.js

[Feat](ABC-1243): Icon Picker - Add new icons

---

src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- Fixed an issue with reordering items in `check-list` variant.
- Fixed an issue with the checkmark not scaling to the size of the checkbox.

[Fix](ABC-1247): List - Not able to reorder items and checkbox styling issues for checklist variant

---

src/modules/base/carousel/carousel.css

**Carousel**
- Fixed styling hook for active indicator border on hover.

[fix] (ABC-1248): Fix styling hook of active indicator in carousel

---

src/modules/base/blockquote/__docs__/blockquote.jsdoc.js
src/modules/base/blockquote/blockquote.css

**Blockquote**
- Added styling hooks for left border (sizing and styling)

[feat](ABC-1249): Blockquote - Added styling hooks for left border

---

src/modules/base/calendar/calendar.css

**Calendar**
- Added styling hooks for hovered selected dates.

[feat] (ABC-1252): Add styling hooks for calendar selected dates

---

src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.js

**Carousel**
- Added `currentpanelchange` event.

[feat] (ABC-1253): Add currentpanelchange event to carousel

---

src/modules/base/colorGradient/__tests__/colorGradient.test.js
src/modules/base/colorGradient/colorGradient.js

**Color Gradient**
- Added delay to `change` event to avoid multiple firings.

[fix] (ABC-1254): Add delay to color gradient change event

---

src/modules/base/card/__tests__/card.test.js
src/modules/base/card/card.js
src/modules/base/layout/__tests__/layout.test.js
src/modules/base/layout/layout.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/item.js
src/modules/base/list/list.html
src/modules/base/list/list.js

[fix] (ABC-1256): Improve list performance

---

src/modules/base/activityTimeline/verticalActivityTimeline.css
src/modules/base/activityTimeline/verticalActivityTimeline.html

- Fix vertical timeline not taking all remaining height

[Fix](ABC-1258): Activity Timeline - Fix component height

---

src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/chipContainer/__docs__/chipContainer.jsdoc.js
src/modules/base/chipContainer/chipContainer.css

- Added top margin to the "show more" button.
**Chip Container**
- Changed `--avonni-chip-container-color-background` styling hook default value to transparent.
- Prevented the list items from overflowing.
- Fixed text overflow issue in dropdown menu.

[Fix] (ABC-1257): Avatar group - Overflow issues

---

src/modules/base/progressCircle/__docs__/progressCircle.jsdoc.js
src/modules/base/progressCircle/progressCircle.css

**Progress Circle**
- Added background color styling hook.
- `--avonni-progress-circle-bar-content-color-background`

[Feat](ABC-1259): Progress Circle - Add background color styling hook

---

src/modules/base/dualListbox/__docs__/dualListbox.jsdoc.js
src/modules/base/dualListbox/__tests__/dualListbox.test.js
src/modules/base/dualListbox/dualListbox.css
src/modules/base/dualListbox/dualListbox.html
src/modules/base/dualListbox/dualListbox.js

- Added boxes color background styling hook
- Added Groups styling hooks
- When avatar, presence was absent when selected
- Fixed avatar presence truncation

[Feat](ABC-1260): Dual Listbox - add background styling hook

---

src/modules/base/combobox/__tests__/combobox.test.js
src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Added the `keepOpenOnSelect` attribute to the combobox.

[feat] (ABC-1264): Add keepOpenOnSelect attribute to combobox

---

src/modules/base/inputCounter/inputCounter.js

**Input Counter**
- Make sure user can't edit the counter with the arrow keys in readOnly

[fix](ABC-1278): Input Counter - Fix change getting dispatched by arrow up down in readOnly

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added new styling hooks for each type (default, toggle and button)

Feat abc 1277 input choice set add styling hooks to buttons

---

src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Added missing documentation
- fixed markup

[fix](ABC-1279): Visual Picker - Added missing doc and fixed markup

---

src/modules/base/inputChoiceSet/inputChoiceSet.css

- Fix fallback values of `--avonni-input-choice-set-option-button[*]-checked-hover` styling hooks

[fix](ABC-1281): Input Choice Set - Fix fallback values of checked hover styling hooks

---

src/modules/base/list/list.js

**List**
- Fixed an issue with the scrollbar in the `check-list` variant.

[Fix](ABC-1282): List - Overflow Scroll should not be displayed

---

src/modules/base/dialog/dialog.html

**Dialog**
- Adjust close button icon to winter 25 release style

[feat](ABC-1285): Dialog - Adjust close button icon to winter 25 style

---

src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/option.js
src/modules/base/primitiveCombobox/primitiveCombobox.html
src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/primitiveCombobox/scrollUtils.js
src/modules/base/primitiveComboboxGroup/primitiveComboboxGroup.html

**Combobox**
- Added automatic infinite loading when `enable-infinite-loading` is present, on top of dispatching the `loadmore` event.

[feat] (ABC-1284): Implement default infinite loading in combobox

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1287): Fix combobox infinite loading

---

src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.css
src/modules/base/calendar/calendar.html
src/modules/base/calendar/calendar.js
src/modules/base/iconPicker/__tests__/iconPicker.test.js

**Calendar**
- Changed the year picker to avoid having to scroll down to the selected year when it is opened.

[fix] (ABC-1288): Use select element instead of combobox for calendar year

---

src/modules/base/inputCounter/inputCounter.html
src/modules/base/inputCounter/inputCounter.js

**Input Counter**
- max and min when percent
- step validations

[fix](ABC-1289): Input Counter - Fix issues with component

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1290): Avoid infinite loop in combobox

---

src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.css
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js

**Metric**
- Add cursor styling hooks for each metric
- `--avonni-metric-primary-cursor`
- `--avonni-metric-secondary-cursor`
- Add click event for each metric
- `primarymetricclick`
- `secondarymetricclick`

[feat](ABC-1293): Metric - Add click interaction for primary and secondary metrics

---

src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

-  Added styling hooks min height max height 
- Added hidden property for items

[Feat](ABC-1295): Visual Picker - Add styling hooks min height max height and hidden property for items

---

src/modules/base/colorPicker/colorPicker.js
src/modules/base/colorPicker/standard.html

- Implemented auto menu alignment.

[feat] (ABC-1296): Implement auto menu alignment in color picker

---

src/modules/base/avatar/__docs__/avatar.jsdoc.js
src/modules/base/metric/__docs__/metric.jsdoc.js
src/modules/base/primitiveAvatar/primitiveAvatar.css

**Avatar**
- Add `--avonni-avatar-scale` styling hook

[Feat](ABC-1298): Avatar - Add scale styling hook for the icon

---

src/modules/base/slider/__docs__/slider.jsdoc.js
src/modules/base/slider/slider.css
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- Support rich text for custom units
- Add custom units styling hooks
- `--avonni-slider-unit-custom-sizing-min-width`
- `--avonni-slider-unit-custom-sizing-max-width`
- `--avonni-slider-unit-custom-line-clamp`
**Slider**
- Fix custom units going out of bounds

[Fix](ABC-1299): Slider - Fix custom labels going out of bounds

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/inputChoiceSet.css

- Added missing background to button type

[Fix](ABC-1300): Input Choice Set - Change variant to neutral for button type

---

src/modules/base/verticalVisualPicker/verticalVisualPicker.css

- Added missing background when selected

[fix](ABC-1301): Vertical Visual Picker - Added missing background when selected

---

src/modules/base/dateTimePicker/__docs__/dateTimePicker.jsdoc.js
src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/dateTimePicker/dateTimePicker.html

- Add styling for label horizontal alignment
- `--avonni-date-time-picker-label-horizontal-alignment`

[feat](ABC-1303): Date Time Picker - Add label horizontal alignment styling hook

---

src/modules/base/datatable/datatable.js
src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/dualListbox/dualListbox.js
src/modules/base/iconPicker/iconPicker.js
src/modules/base/kanban/groupBuilder.js
src/modules/base/kanban/kanban.js
src/modules/base/list/list.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/path/__tests__/path.test.js
src/modules/base/path/path.js
src/modules/base/schedulerUtils/event.js
src/modules/base/tree/treeData.js
src/modules/base/utilsPrivate/__tests__/utility.test.js
src/modules/base/utilsPrivate/utility.js
src/modules/base/utilsPrivate/utilsPrivate.js

[feat] (ABC-1304): Avoid use of JSON when possible

---

src/modules/base/list/__docs__/data.js
src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- Removed `itemclick` event on checkbox for check-list variant.

[Fix](ABC-1307): List - Click on checkbox triggers click on item for check-list variant

---

src/modules/base/primitiveActions/primitiveActions.html

**List**
- Fixed an issue with actions dropdown menu going out of bounds.

[fix](ABC-1310): List - Actions dropdown going out of bounds

---

src/modules/base/primitiveCombobox/primitiveCombobox.js
src/modules/base/storybookWrappers/combobox/combobox.js

No changes compared to the previous package version.

[fix] (ABC-1309): Prevent infinite loading loop in combobox

---

src/modules/base/inputPen/inputPen.css
src/modules/base/inputPen/inputPen.html

**Input Pen**
- Changed size-picker combobox to avonni combobox

[fix](ABC-1311): Input Pen - Changed size-picker combobox to avonni combobox

---

src/modules/base/pillContainer/__docs__/pillContainer.jsdoc.js
src/modules/base/pillContainer/__tests__/pillContainer.test.js
src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js
src/modules/base/primitivePill/primitivePill.css
src/modules/base/primitivePill/primitivePill.html
src/modules/base/primitivePill/primitivePill.js

- Add `itemclick` event
- Add dropdown sizing styling hooks with default size
- `--avonni-pill-container-dropdown-sizing-width`, default to 13rem
- `--avonni-pill-container-dropdown-sizing-max-height`, defaults to 17.5rem
- Fix pills going out of container in single line
- Fix error when scrolling in 'More' dropdown

[Feat](ABC-1312): Pill Container - Add item click event

---

src/modules/base/slider/__docs__/slider.jsdoc.js
src/modules/base/slider/slider.css
src/modules/base/slider/slider.js

**Slider**
- Add thumb active background color styling hook
- `--avonni-slider-thumb-color-active`

[Feat](ABC-1313): Slider - Add thumb active styling hook color

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

**Input choice set**
- Fixed label horizontal alignment when toggle

[fix](ABC-1316): Input Choice Set - Fixed label horizontal alignment when toggle

---

src/modules/base/qrcode/__tests__/qrcode.test.js
src/modules/base/qrcode/qrcode.js

**Qr Code**
- Fixed issue with component becoming black

[fix](ABC-1317): Qr Code - Fixed issue with component becoming black

---

src/modules/base/colorPicker/__tests__/colorPicker.test.js
src/modules/base/colorPicker/shared.css
src/modules/base/colorPicker/standard.html
src/modules/base/qrcode/__tests__/qrcode.test.js
src/modules/base/qrcode/qrcode.js

- Reduced spacing to match the lightning input color

[Fix](ABC-1318) Color Picker - Reduce spacing to match the lightning input color

---

src/modules/base/colorPicker/standard.html

[fix](ABC-1319): Color Picker - Added padding to label

---

src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Button color when disabled
- Sizing issue

[Fix](ABC-1321): Input Choice Set - When disabled selected button stay blue, Sizing Issue

---

src/modules/base/carousel/__examples__/imagePositionLeft/imagePositionLeft.js
src/modules/base/image/__docs__/image.stories.js
src/modules/base/image/__examples__/base/base.html
src/modules/base/image/__examples__/baseLarge/baseLarge.html
src/modules/base/image/__examples__/baseSmall/baseSmall.html
src/modules/base/image/__examples__/baseWithLazyLoading/baseWithLazyLoading.js
src/modules/base/image/__examples__/center/center.html
src/modules/base/image/__examples__/compare/compare.html
src/modules/base/image/__examples__/cropImageStaticThumbnailMobile/cropImageStaticThumbnailMobile.html
src/modules/base/image/__examples__/magnifier/magnifier.html
src/modules/base/image/__examples__/right/right.html
src/modules/base/image/__examples__/thumbnail/thumbnail.html
src/modules/base/image/image.css
src/modules/base/image/image.html
src/modules/base/list/__examples__/images/images.js

**Image**
- Fixed the height of the image when the position is set to left or right.
- Fixed issue with the original image appearing under the compare image.

[Fix](ABC-1322): Image - Height issue when position is left or right

---

src/modules/base/image/image.css

**Image**
- Removed the background color on the compare image.

[Fix](ABC-1323): Image - Remove white background color on the compare image

---

jest-mock/components/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/storybookWrappers/tree/tree.html
src/modules/base/storybookWrappers/tree/tree.js
src/modules/base/tree/__docs__/tree.stories.js
src/modules/base/tree/__examples__/collapseDisabled/collapseDisabled.html
src/modules/base/tree/__examples__/collapseDisabled/collapseDisabled.js
src/modules/base/tree/__examples__/tree.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.html
src/modules/base/tree/tree.js

**Tree**
- Added attribute `collapse-disabled`.

[feat](ABC-1325): Tree - Add collapseDisabled attribute

---

src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.stories.js
src/modules/base/inputChoiceSet/__examples__/buttons/buttons.js
src/modules/base/inputChoiceSet/__examples__/buttonsHorizontal/buttonsHorizontal.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js
src/modules/base/tooltipLibrary/tooltipLibrary.js

[Feat](ABC-1326): Input Choice Set - Add tooltip for button on hover

---

src/modules/base/profileCard/__tests__/profileCard.test.js
src/modules/base/profileCard/profileCard.js

- Added `onprivateprofilecardrendered` event.

[feat](ABC-1327): Profile Card - Add callback event to refresh the slots visibility

---

src/modules/base/carousel/__docs__/carousel.jsdoc.js
src/modules/base/carousel/__docs__/data.js
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js
src/modules/base/carousel/paginationItem.js
src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
src/modules/base/primitiveCarouselItem/noTag.html
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js
src/modules/base/primitiveCarouselItem/shared.css
src/modules/base/primitiveCarouselItem/tag.html

**Carousel**
- Added new action styling hooks
**Carousel**
- Fixed issue with actionsVariant

[Fix](ABC-1315): carousel - Review action buttons button icon vs button vs button menu

---

src/modules/base/profileCard/__tests__/profileCard.test.js
src/modules/base/profileCard/profileCard.css
src/modules/base/profileCard/profileCard.html
src/modules/base/profileCard/profileCard.js

- Fixed position issue for the avatar and actions.

[Fix](ABC-1328): Profile Card - Fix avatar position issue

---

src/modules/base/button/__docs__/button.stories.js
src/modules/base/button/__examples__/button.js
src/modules/base/button/__examples__/sizes/sizes.html
src/modules/base/button/__examples__/sizes/sizes.js
src/modules/base/button/__tests__/button.test.js
src/modules/base/button/button.css
src/modules/base/button/button.html
src/modules/base/button/button.js
src/modules/base/buttonIcon/__docs__/buttonIcon.stories.js
src/modules/base/buttonIcon/__examples__/buttonIcon.js
src/modules/base/buttonIcon/__examples__/sizes/sizes.html
src/modules/base/buttonIcon/__examples__/sizes/sizes.js
src/modules/base/buttonIcon/__tests__/buttonIcon.test.js
src/modules/base/buttonIcon/buttonIcon.css
src/modules/base/buttonIcon/buttonIcon.html
src/modules/base/buttonIcon/buttonIcon.js
src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/buttonMenu/__examples__/buttonMenuBase.js
src/modules/base/buttonMenu/__examples__/buttonMenuIllustration.js
src/modules/base/buttonMenu/__examples__/sizes/sizes.html
src/modules/base/buttonMenu/__examples__/sizes/sizes.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.css
src/modules/base/buttonMenu/buttonMenu.html
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/primitiveButton/primitiveButton.js

**Button, Button Icon and Button Menu**
- Add `isButtonLoading` attribute. Shows a spinner on top of the button.

[Feat](ABC-1338): Button Components - Add isButtonLoading attribute

---

src/modules/base/dateTimeUtils/__tests__/dateTime.test.js
src/modules/base/dateTimeUtils/dateTime.js
src/modules/base/dateTimeUtils/formatter.js

[fix] (ABC-1339): Fix DateTime toISO method when time zone is not locale

---

lwc.config.json
src/modules/base/dateTimePicker/dateTimePicker.js
src/modules/base/scheduler/scheduler.js
src/modules/base/timeZones/timeZones.js
src/modules/base/timeZones/timeZones.js-meta.xml

No differences compared to previous package version.

[fix] (ABC-1342): Stay on selected date when scheduler time zone changes

---

lwc.config.json
src/modules/base/primitiveCombobox/primitiveCombobox.js

[version] (ABC-1344): Expose combobox primitives in package

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- When using `dropdownAlignment` = "auto", prioritize a left alignment

[feat](ABC-1343): Primitive Combobox - Prioritize left dropdown alignment when using auto

---

src/modules/base/inputDateRange/inputDateRange.js

[fix] (ABC-1345): Fix date range popover not closing after picking today

---

src/modules/base/metric/__docs__/metric.stories.js
src/modules/base/metric/__examples__/metric.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js

**Metric**
- Added attribute `label-position`.

[feat](ABC-1347): Metric - Add new attribute "Label Position"

---

src/modules/base/combobox/__docs__/combobox.stories.js
src/modules/base/combobox/__examples__/required/required.html
src/modules/base/combobox/__examples__/required/required.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevent deselection for `required` and non multi-selected input

[Feat](ABC-1349): Combobox - Prevent deselection for required and non multi-select input

---

src/modules/base/slider/slider.css
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- Fixed issue with pin not being displayed in the mobile app.
- Fixed position issue with slider buttons in the mobile app.

[Fix](ABC-1351): Slider - Bugs on mobile app

---

src/modules/base/inputDateRange/inputDateRange.css
src/modules/base/inputDateRange/inputDateRange.html
src/modules/base/inputDateRange/inputDateRange.js

- Fix alignment issues
- Support small containers

[Fix](ABC-1355): Input Date Range - Fix alignments and wrap in mobile

---

src/modules/base/metric/__docs__/metric.jsdoc.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.css
src/modules/base/metric/metric.js

**Metric**
- Added avatar vertical alignment styling hook.
-  `--avonni-metric-avatar-vertical-alignment`

[fix](ABC-1354): Metric - Avatar alignment when left or right

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.css
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- Fixed the position of the pin in mobile app.
- Fixed scrolling issue with vertical slider.

[Fix](ABC-1356): Slider - Fix pin position in mobile app

---

src/modules/base/progressBar/__tests__/progressBar.test.js
src/modules/base/progressBar/progressBar.js

- Fixed displayed value on mobile app.

[Fix](ABC-1361): Progress Bar - Displayed value doesn't match actual progress on mobile

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.css
src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- Allow users to select multiple line items and drag/drop them as a group for faster reordering.

[Feat](ABC-1346): List - Allow users to select multiple line items and drag/drop them as a group for faster reordering

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Allowed 0 as an option value.

[fix] (ABC-1364): Accept 0 as a combobox option value

---

src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.css
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.css
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js
src/modules/base/schedulerUtils/eventData.js

**Scheduler**
- Fixed events with no end overlap.
- Fixed `zoom-to-fit` in vertical scheduler timeline.
- Fixed display of all-day events in the timeline, when their start is in the past, but their end is in the future.
- Added a faded background to the "more" buttons, in the monthly calendar display.

[fix] (ABC-1363): Fix scheduler bugs

---

src/modules/base/primitiveRelationshipGraphGroup/__tests__/primitiveRelationshipGraphGroup.test.js
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.css
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js
src/modules/base/primitiveRelationshipGraphItem/primitiveRelationshipGraphItem.js
src/modules/base/primitiveRelationshipGraphLevel/__tests__/primitiveRelationshipGraphLevel.test.js
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.html
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.js
src/modules/base/relationshipGraph/relationshipGraph.css
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

- Added `toggle` event for groups.
- Added `isLoading` attribute to groups.
- Display a message when the group has no items.
- Removed unwanted line border when selecting an item.

[Feat](ABC-1333): Relationship Graph - Refactor

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1369): Reset infinite options scroll when options change

---

src/modules/base/primitiveTreeItem/primitiveTreeItem.html

**Tree**
- Hide the actions button menu if it has no actions to display.

[feat](ABC-1368): Tree - Hide actions button menu if empty

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1371): Reset multi-select combobox level when closing it

---

src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html

- If an item has an ISO date for `datetimeValue`, display the date at midnight on that day, whatever the current time zone.

[feat] (ABC-1372): Normalize day only dates in activity timeline

---

src/modules/base/relationshipGraph/relationshipGraph.js

- Fixed an issue where empty groups were not showing.

[fix](ABC-1374): Relationship Graph - Fix issue with empty groups

---

src/modules/base/relationshipGraph/__tests__/relationshipGraph.test.js
src/modules/base/relationshipGraph/relationshipGraph.css
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

- Removed the top gray line displayed at the root if the graph has no header or actions.

[feat](ABC-1376): Relationship Graph - Remove top gray line if no header

---

src/modules/base/primitiveRelationshipGraphGroup/__tests__/primitiveRelationshipGraphGroup.test.js
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.css
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js
src/modules/base/primitiveRelationshipGraphItem/__tests__/primitiveRelationshipGraphItem.test.js
src/modules/base/primitiveRelationshipGraphLevel/__tests__/data.js
src/modules/base/primitiveRelationshipGraphLevel/__tests__/primitiveRelationshipGraphLevel.test.js
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.html
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.js
src/modules/base/relationshipGraph/__tests__/data.js
src/modules/base/relationshipGraph/__tests__/relationshipGraph.test.js
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

- Removed the gray line at the root if the graph has no header or actions.

[Feat](ABC-1379): Relationship Graph - Remove gray line at the root if no header

---

src/modules/base/primitiveRelationshipGraphItem/primitiveRelationshipGraphItem.js
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

- Added gray line at the root for header actions.

[Feat](ABC-1380): Relationship Graph - Display gray line for header actions

---

src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/filterMenu/__tests__/nestedItemsUtils.test.js
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenu/item.js
src/modules/base/filterMenu/nestedItemsUtils.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js

[feat] (ABC-1375): Add select immediate children action in filter menu

---

jest-mock/components/base/buttonMenu/buttonMenu.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js

- Added `close` method.
- Fixed the `auto` value of `menu-alignment`.

[feat] (ABC-1385): Implement auto alignment and close in button menu

---

src/modules/base/carousel/__docs__/carousel.stories.js
src/modules/base/carousel/__examples__/carousel.js
src/modules/base/carousel/__examples__/infiniteLoadingCarousel.js
src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js
src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
src/modules/base/primitiveCarouselItem/noTag.html
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js
src/modules/base/primitiveCarouselItem/shared.css
src/modules/base/primitiveCarouselItem/tag.html

**Carousel**
- Added attribute `crop-fit`.

[feat] (ABC-1387) Carousel - Add new attribute "Crop Fit"

---

src/modules/base/alert/__tests__/alert.test.js
src/modules/base/alert/alert.css
src/modules/base/alert/alert.js

**Alert**
- Removed the close icon space when the alert is not dismissible.

[fix] (ABC-1388): Remove the icon space when alert is not dismissible

---

src/modules/base/buttonMenu/__docs__/buttonMenu.stories.js
src/modules/base/buttonMenu/__examples__/bareWithPrefixIcon/bareWithPrefixIcon.html
src/modules/base/buttonMenu/__examples__/bareWithPrefixIcon/bareWithPrefixIcon.js
src/modules/base/buttonMenu/__examples__/buttonMenuBase.js
src/modules/base/buttonMenu/__examples__/buttonMenuIllustration.js
src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.html
src/modules/base/buttonMenu/buttonMenu.js
src/modules/base/storybookWrappers/buttonMenu/base.html
src/modules/base/storybookWrappers/buttonMenu/base.js
src/modules/base/storybookWrappers/buttonMenu/illustration.html
src/modules/base/storybookWrappers/buttonMenu/illustration.js

- Added `prefix-icon-name` attribute.

[feat] (ABC-1390): Add prefix icon name to button menu

---

src/modules/base/primitiveRelationshipGraphGroup/__tests__/primitiveRelationshipGraphGroup.test.js
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.css
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js

- Modified the graph group header into an expandable section, allowing users to collapse or expand the group by clicking anywhere on the title.

[Feat](ABC-1389): Relationship Graph - Use expandable section for the group header

---

src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.css
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html

- Fixed the alignment between the label and the collapse icon.

[fix](ABC-1394): Relationship Graph - Collapsible icon is not aligned with label

---

src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphItem/__tests__/primitiveRelationshipGraphItem.test.js
src/modules/base/primitiveRelationshipGraphItem/primitiveRelationshipGraphItem.css
src/modules/base/primitiveRelationshipGraphItem/primitiveRelationshipGraphItem.html
src/modules/base/primitiveRelationshipGraphItem/primitiveRelationshipGraphItem.js

- Added `disabled` attribute to items.
- Added styling hooks:
-  `--avonni-relationship-graph-text-color-disabled`
- `--avonni-relationship-graph-color-background-disabled`
- `--avonni-relationship-graph-color-border-background-disabled`

[feat](ABC-1396): Relationship Graph - Item - Add "disabled" attribute

---

src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
-  Included action and sortable icon in item body

[fix](ABC-1391): List - Included action and sortable icon in item body

---

src/modules/base/list/list.css

**List**
- Border Color not apply on card divider

[fix](ABC-1392): List - Border Color not apply on card divider

---

src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.js
src/modules/base/primitiveRelationshipGraphGroup/__tests__/primitiveRelationshipGraphGroup.test.js
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.css
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js

- Removed focus outline on mouse click.
- Removed focus outline on mouse click.

[Feat](ABC-1398): Expandable Section - Remove focus outline on click

---

src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.js

- Show more was appearing when max count was equal to items count

[fix](ABC-1399): Avatar Group - Fix show more button issue

---

src/modules/base/list/list.css

**List**
- Remove unnecessary margin around actions container

[fix](ABC-1400): List - Remove unnecessary margin around actions container

---

src/modules/base/metric/__docs__/metric.stories.js
src/modules/base/metric/__examples__/baseEmptyWithError/baseEmptyWithError.html
src/modules/base/metric/__examples__/baseEmptyWithError/baseEmptyWithError.js
src/modules/base/metric/__examples__/metric.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.css
src/modules/base/metric/metric.html
src/modules/base/metric/metric.js

**Metric**
- Add `errorMessage` attribute

[Feat](ABC-1404): Metric - Add errorMessage attribute

---

src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.css
src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.html
src/modules/base/primitiveVisualPickerHeader/primitiveVisualPickerHeader.js
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.css
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.html
src/modules/base/primitiveVisualPickerTitle/primitiveVisualPickerTitle.js
src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Added selected text styling hooks

[feat](ABC-1407): Visual Picker - Added selected text styling hooks

---

src/modules/base/outputData/__tests__/outputData.test.js
src/modules/base/outputData/outputData.html
src/modules/base/outputData/outputData.js

**Output Data**
- Show empty value for null or undefined values instead of normalizing to 0 for number fields

[Feat](ABC-1409): Output Data - Support empty value

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__examples__/activityTimeline.js
src/modules/base/activityTimeline/__examples__/hideVerticalBar/hideVerticalBar.html
src/modules/base/activityTimeline/__examples__/hideVerticalBar/hideVerticalBar.js
src/modules/base/activityTimeline/__examples__/infiniteLoadingActivityTimeline.js
src/modules/base/activityTimeline/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/__tests__/horizontalActivityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/activityTimeline/horizontalActivityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js

**Activity Timeline*
- Added new attributes: disableUpcomingGroup, hideVerticalBar
**Activity Timeline Item*
- Added new attribute: endDateValue

[Feat](ABC-1408): Activity Timeline - Enhanced event display.

---

src/modules/base/buttonMenu/__tests__/buttonMenu.test.js
src/modules/base/buttonMenu/buttonMenu.js

- Position of button menu dropdown is fixed instead of absolute when menu alignment is auto

[fix] (ABC-1401): Button Menu - Dropdown position fixed

---

src/modules/base/primitiveDropdownMenu/primitiveDropdownMenu.html
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/scheduler/__docs__/scheduler.jsdoc.js
src/modules/base/scheduler/__tests__/data.js
src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/scheduler.html
src/modules/base/scheduler/scheduler.js

**Scheduler**
- Add disabled and hidden to actions

[feat](ABC-1433): Scheduler - Added disabled and hidden attributes to actions

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- fixed bugs with unit attributes

[Fix](ABC-1435): Slider - fixed bugs with unit attributes

---

src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.js
src/modules/base/tree/treeData.js

**Tree**
- Fixed tree item not expanding when sorting and hovering over a collapsed item.

[Bugfix] (ABC-1438): Tree - Fix expand not working when sorting and hovering over a collapsed item

---

src/modules/base/colorPicker/colorPicker.js
src/modules/base/colorPicker/standard.html
src/modules/base/iconPicker/iconPicker.html
src/modules/base/slider/__docs__/slider.stories.js
src/modules/base/slider/__examples__/customLabelSlider.js
src/modules/base/slider/__examples__/maxHeightSlider.js
src/modules/base/slider/__examples__/verticalSlider.js
src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js
src/modules/base/storybookWrappers/slider/customLabelSlider/customLabelSlider.html
src/modules/base/storybookWrappers/slider/customLabelSlider/customLabelSlider.js
src/modules/base/storybookWrappers/slider/maxHeightSlider/maxHeightSlider.html
src/modules/base/storybookWrappers/slider/maxHeightSlider/maxHeightSlider.js
src/modules/base/storybookWrappers/slider/verticalSlider/verticalSlider.html
src/modules/base/storybookWrappers/slider/verticalSlider/verticalSlider.js
src/modules/base/tree/tree.html

- Added accessible names to button and input.
- Added aria label to value input.
**Slider**
- Added `alternativeText` attribute.
- Show pin on keyboard focus.
**Tree**
- Fixed accessibility HTML heading level order.

[Feat](ABC-1439): Input - Accessibility - Review ARIA attributes in form

---

jest-mock/components/base/primitiveTreeItem/primitiveTreeItem.js
jest-mock/components/lightning/tree/tree.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.css
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/storybookWrappers/tree/tree.html
src/modules/base/storybookWrappers/tree/tree.js
src/modules/base/tree/__docs__/data.js
src/modules/base/tree/__docs__/tree.jsdoc.js
src/modules/base/tree/__docs__/tree.stories.js
src/modules/base/tree/__examples__/rootSlottableTypes/rootSlottableTypes.html
src/modules/base/tree/__examples__/rootSlottableTypes/rootSlottableTypes.js
src/modules/base/tree/__examples__/tree.js
src/modules/base/tree/__tests__/data.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.html
src/modules/base/tree/tree.js
src/modules/base/tree/treeData.js
src/modules/base/tree/treeNode.js

**Tree**
- Added attribute `root-slottable-types`
- Added attributes to `items`: 
- `hiddenActions`
- `noSlots`
- `slottableTypes`
- `type`
- `unselectable`

[Feat] (ABC-1423): Tree - Add attributes rootSlottableTypes, noSlots, unselectable, hiddenActions, type and slottableTypes

---

src/modules/base/buttonIcon/__docs__/buttonIcon.jsdoc.js
src/modules/base/buttonIcon/buttonIcon.css

**Button Icon**
- Added spacing styling hooks

[feat](ABC-1395): Button Icon - Added spacing styling hooks

---

src/modules/base/button/__docs__/button.stories.js
src/modules/base/button/__examples__/button.js
src/modules/base/button/__tests__/button.test.js
src/modules/base/button/button.html
src/modules/base/buttonIcon/__docs__/buttonIcon.stories.js
src/modules/base/buttonIcon/__examples__/buttonIcon.js
src/modules/base/buttonIcon/__tests__/buttonIcon.test.js
src/modules/base/buttonIcon/buttonIcon.html
src/modules/base/primitiveActions/primitiveActions.html
src/modules/base/primitiveCarouselItem/noTag.html
src/modules/base/primitiveCarouselItem/tag.html

**Button**
- Added `title` attribute.
**Button Icon**
- Added `title` attribute.
**Carousel**
- Added title attribute to item action.
**Primitive Actions**
- Added title attribute to item action.

[feat](ABC-1447): Button - Add title attribute

---

jest-mock/components/lightning/avatar/avatar.js
src/modules/base/avatar/__docs__/avatar.stories.js
src/modules/base/avatar/__examples__/avatar.js
src/modules/base/avatar/__examples__/baseWithIconPositionCenter/baseWithIconPositionCenter.html
src/modules/base/avatar/__examples__/baseWithIconPositionCenter/baseWithIconPositionCenter.js
src/modules/base/avatar/__examples__/baseWithIconPositionEnd/baseWithIconPositionEnd.html
src/modules/base/avatar/__examples__/baseWithIconPositionEnd/baseWithIconPositionEnd.js
src/modules/base/avatar/__examples__/baseWithIconPositionStart/baseWithIconPositionStart.html
src/modules/base/avatar/__examples__/baseWithIconPositionStart/baseWithIconPositionStart.js
src/modules/base/avatar/__tests__/avatar.test.js
src/modules/base/avatar/avatar.html
src/modules/base/avatar/avatar.js
src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/__docs__/avatarGroup.stories.js
src/modules/base/avatarGroup/__examples__/base.js
src/modules/base/avatarGroup/__examples__/infiniteLoading.js
src/modules/base/avatarGroup/__examples__/infiniteLoadingUsingShowMore.js
src/modules/base/avatarGroup/__tests__/avatarGroup.test.js
src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js
src/modules/base/mediaObject/mediaObject.js

- Added the `iconPosition` attribute.

[Feat](ABC-1450): Avatar Group - Add Icon Position Attribute

---

src/modules/base/activityTimeline/horizontalActivityTimeline.css
src/modules/base/activityTimeline/horizontalActivityTimeline.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html

- Added description line clamp styling hook:
- `--avonni-activity-timeline-item-description-line-clamp`

[feat](ABC-1440): Activity Time Line - Description - Add truncate styling hook

---

src/modules/base/profileCard/__tests__/profileCard.test.js
src/modules/base/profileCard/profileCard.css
src/modules/base/profileCard/profileCard.html
src/modules/base/profileCard/profileCard.js

- Fixed the display of the avatar and icon

[Feat] (ABC-1451): Profile Card - Review Avatar Position

---

src/modules/base/carousel/__docs__/carousel.stories.js
src/modules/base/carousel/__docs__/data.js
src/modules/base/carousel/__examples__/carousel.js
src/modules/base/carousel/__examples__/infiniteLoadingCarousel.js
src/modules/base/carousel/__examples__/itemsWithNoImageAndError/ItemsWithNoImageAndError.html
src/modules/base/carousel/__examples__/itemsWithNoImageAndError/ItemsWithNoImageAndError.js
src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.html
src/modules/base/carousel/carousel.js
src/modules/base/image/__docs__/image.stories.js
src/modules/base/image/__examples__/image.js
src/modules/base/image/__examples__/imageError/imageError.html
src/modules/base/image/__examples__/imageError/imageError.js
src/modules/base/image/__examples__/imageList.js
src/modules/base/image/__examples__/noImage/noImage.html
src/modules/base/image/__examples__/noImage/noImage.js
src/modules/base/image/__tests__/image.test.js
src/modules/base/image/image.html
src/modules/base/image/image.js
src/modules/base/primitiveCarouselItem/__tests__/primitiveCarouselItem.test.js
src/modules/base/primitiveCarouselItem/noTag.html
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.js
src/modules/base/primitiveCarouselItem/tag.html
src/modules/base/storybookWrappers/carousel/infiniteLoading.js
src/modules/base/storybookWrappers/image/image.html
src/modules/base/storybookWrappers/image/image.js
src/modules/base/storybookWrappers/image/imageList.html
src/modules/base/storybookWrappers/image/imageList.js

**Carousel && Image**
- imageErrorLabel
- noImageLabel

[Feat](ABC-1456): Image components - handle image error and no source

---

src/modules/base/primitiveCombobox/__tests__/primitiveCombobox.test.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Clear the search value when changing level with multi-level groups.

[feat] (ABC-1446): Clear combobox search when changing level

---

src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.css
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html

[fix](ABC-1457): Primitive Activity Timeline - Fixed title not truncating

---

src/modules/base/iconPicker/iconPicker.css

- Fix no background color for certain new icons in experience builder

[fix](ABC-1468)(XPC-19): Icon Picker - Add missing classes definitions for new icons for experience custom property editor

---

src/modules/base/alert/alert.css

**Alert**
- Updated the style to allow the parent to set the alert height.

[feat] (ABC-1465): Allow alert height to be controlled by its parent

---

src/modules/base/inputChoiceSet/__docs__/inputChoiceSet.jsdoc.js
src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceOption.js
src/modules/base/inputChoiceSet/inputChoiceSet.html
src/modules/base/inputChoiceSet/inputChoiceSet.js

- Added `hidden` and `disabled` properties to options.

[feat] (ABC-1469): Add hidden and disabled props to input choice set opt

---

src/modules/base/inputData/__tests__/inputData.test.js
src/modules/base/inputData/inputData.js

**Input Data**
- Fix 0 value getting normalized to null

[Fix](ABC-1470): Input Data - Do not normalize 0 value to null
