avonni/base-components

src/modules/base/image/__docs__/image.stories.js
src/modules/base/image/__examples__/image.js
src/modules/base/image/__tests__/image.test.js
src/modules/base/image/image.css
src/modules/base/image/image.html
src/modules/base/image/image.js

- Added crop-size property: values -> 1x1, 4x3, 16x9, none
- Added crop-fit property : values -> 'cover', 'contain', 'fill', 'none'
- Added crop-position-X and crop-position-Y
Features:
- When no width specified, crops the image based on current container width
- When a width is specified, this becomes the crop width and subsequent 1:1, 4:3, 16:9 dimensions
- Can reposition point of interest in cropped image by using the position-X and Y
- All sizes responsive with or without width specified
- Cover and Contain crop-fit allow for point of interest preservation on resize
Tests : 
- Crop size 16x9, 1x1, 4x3
- Crop fit ‘cover’, ‘contain’, ‘fill’, ‘none’
- Crop Position X - Y
- Cropped Img Alignment - left, right, centre
- Cropped Ratio with width
Fixes :
- When not cropped, the image …

(feat) (abc 200) Crop Size property / Image crop properties

---

jsdoc/jsdoc.config.json
jsdoc/publish.js

- Show properties without a getter/setter in output
- Add recursion to config to simplify JSDoc script

[fix] (ABC-303): Fix JSDoc config

---

src/modules/base/inputRichText/inputRichText.js
src/modules/base/inputToggle/inputToggle.js

- Stop propagation of default `<input>` change event in inputToggle.
- Prevent console warning when an empty string value is given to the inputRichText

[fix] (ABC-337): Fix input toggle change event and input rich text warning

---

src/modules/base/carousel/__docs__/carousel.jsdoc.js
src/modules/base/chip/__docs__/chip.jsdoc.js
src/modules/base/chip/chip.css
src/modules/base/combobox/combobox.css
src/modules/base/combobox/combobox.js
src/modules/base/inputCounter/__tests__/inputCounter.test.js
src/modules/base/inputCounter/inputCounter.html
src/modules/base/inputCounter/inputCounter.js
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.css
src/modules/base/primitiveCarouselItem/primitiveCarouselItem.html
src/modules/base/qrcode/__docs__/qrcode.jsdoc.js
src/modules/base/qrcode/__docs__/qrcode.stories.js
src/modules/base/qrcode/__tests__/qrcode.test.js
src/modules/base/qrcode/qrcode.css
src/modules/base/qrcode/qrcode.js
src/modules/base/range/__docs__/range.jsdoc.js
src/modules/base/range/range.css
src/modules/base/range/range.html
src/modules/base/separator/__docs__/separator.jsdoc.js
src/modules/base/separator/separator.css
src/modules/base/separator/separator.js

- ABC-438: Add text styling hooks to carousel
- ABC-439: Add styling hooks for outline in chip
- ABC-441: Add text styling hooks to input counter
- ABC-442 / ABC-443: Fixed styling hooks for color and background in qrcode
- ABC-444: Add styling hooks for icon in separator
- Change styling hooks name for header in range

Feat ABC-437 Complementary adding styling hooks

---

src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/tree/__tests__/data.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.js
src/modules/base/tree/treeData.js

**Fixes:**
- `edit` action is cancelable.
- Edit popover closes when an action is clicked.
- Switching between single and multi select does not trigger an error.
**Features:**
- Add `levelPath` to `actionclick`, `select` and `change` events.
- Add `bounds` to `select` and `actionclick` events.

[feat][fix] (ABC-484): Improve and fix tree events

---

jest-mock/components/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/storybookWrappers/tree/tree.html
src/modules/base/storybookWrappers/tree/tree.js
src/modules/base/tree/__docs__/tree.stories.js
src/modules/base/tree/__examples__/multiSelectNoCascade/multiSelectNoCascade.html
src/modules/base/tree/__examples__/multiSelectNoCascade/multiSelectNoCascade.js
src/modules/base/tree/__examples__/tree.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.html
src/modules/base/tree/tree.js
src/modules/base/tree/treeData.js

**Tree**
- Add `disable-selection-cascade` attribute
**Tree**
- Fix the selection of an item through a click on its checkbox.

[feat] (ABC-508): Add option to select parent w/o children in tree

---

src/modules/base/list/__docs__/list.jsdoc.js

Reverted all to previous versions. Corrected on release.

[fix][docs] Correct hook types, no ',' in @type

---

jest-mock/components/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/storybookWrappers/tree/tree.html
src/modules/base/storybookWrappers/tree/tree.js
src/modules/base/tree/__docs__/tree.stories.js
src/modules/base/tree/__examples__/independentMultiSelect/independentMultiSelect.html
src/modules/base/tree/__examples__/independentMultiSelect/independentMultiSelect.js
src/modules/base/tree/__examples__/tree.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.html
src/modules/base/tree/tree.js
src/modules/base/tree/treeData.js

Fixes for pull request [#274](https://github.com/avonni/base-components/pull/274):
- Rename `disable-selection-cascade` to `independent-multi-select`.
- Fix multi-selection not cascading through more than one level.

[fix] (ABC-510): Fix tree multi select and rename disable selection cascade

---

package-lock.json
src/modules/base/calendar/__docs__/calendar.jsdoc.js
src/modules/base/calendar/__docs__/calendar.stories.js
src/modules/base/calendar/__examples__/baseWithWeekNumber/baseWithWeekNumber.js
src/modules/base/calendar/__examples__/calendar.js
src/modules/base/calendar/__examples__/interval/interval.js
src/modules/base/calendar/__examples__/labels/labels.html
src/modules/base/calendar/__examples__/labels/labels.js
src/modules/base/calendar/__examples__/markedDates/markedDates.js
src/modules/base/calendar/__examples__/multiple/multiple.js
src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.css
src/modules/base/calendar/calendar.html
src/modules/base/calendar/calendar.js
src/modules/base/chip/__docs__/chip.jsdoc.js
src/modules/base/chip/chip.css
src/modules/base/chip/chip.html
src/modules/base/inputDateRange/inputDateRange.js
src/modules/base/list/__docs__/list.jsdoc.js
src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js

I tried to explore prior commits in the last branch and ended up with a messy mix of old and new code.
https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/352976919/Calendar
Set dimensions for default and labeled calendar
Default: 40 x 40px
Labeled: w x h, 70 x 60px
Updated calendar interval selection behavior.
In interval mode, when clicking a date before a selection, the selection extends to include that day instead of resetting the selection.
Fix: Hover borders no longer cause dimension changes.
https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/1424064563/Chip
Add hooks to chip
--avonni-chip-spacing-block-start
--avonni-chip-spacing-block-end
--avonni-chip-spacing-inline-start
--avonni-chip-spacing-inline-end
added truncated text when label larger than chip
max-width 100% …

ABC-512 Add label to calendar dates

---

src/modules/base/list/list.js
src/modules/base/utilsPrivate/normalize.js
src/modules/base/utilsPrivate/utilsPrivate.js

_This pull request should not be reflected in the release notes, only utils have been changed._
- Added `normalizeObject` (only accepts direct prototypes of `Object` — not `Date`, `Array`, `null`, etc.).
- `normalizeArray` now accepts a second argument: the type of the array entries. Valid values are `string`, `number`, `boolean` and `object`.

[feat] (ABC-457): Add normalizeObject and improve normalizeArray

---

src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.js
src/modules/base/dateTimePicker/dateTimePicker.js
src/modules/base/inputDateRange/inputDateRange.js

**Calendar**
- The `change` event value is an ISO formatted string if the selection mode is `single`, or an array of ISO formatted strings otherwise.

[fix] (ABC-528): Dispatch string or array value in calendar change event

---

src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- In sortable lists with actions, prevented an item from being dragged when the user clicked and held an action menu item.

[fix] (ABC-529): Do not allow dragging of the action menu in list

---

src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Fixes**
- If new options are set after a `levelchange` event, the combobox will stay open and display the updated options for the level picked.

[fix] (ABC-536): Keep the combobox opened on the right level when new options are set

---

src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js
src/modules/base/list/__docs__/list.jsdoc.js

**Combobox**
- Fixed `selected-options-direction` with vertical value.

[fix] (ABC-541): Fix vertical selected options in combobox

---

src/modules/base/combobox/combobox.html
src/modules/base/combobox/combobox.js

**Combobox**
- Removed the "remove" action on selected options, when the combobox is disabled.

[fix] (ABC-545): Prevent selected opt. removal when combobox is disabled

---

src/modules/base/pillContainer/__docs__/pillContainer.jsdoc.js

The labels are present already but the doc was missing. 
https://avonnicreator.atlassian.net/wiki/spaces/ABC/pages/2109734917/Pill+Container

Add name to fields in pill container items

---

src/modules/base/inputCounter/inputCounter.css

Input Counter
- '-' and '+' now scale relative to top of input rather than height of element, which was bigger when a help message was shown

[fix] (ABC-580): Input Counter - Fix '-' and '+' alignment 

---

src/modules/base/inputRichText/inputRichText.js

**Input Rich Text**
- Added documentation for `insertTextAtCursor()` and `getFormat()` methods.
- Added `getSelection()` method.

[feat][doc] (ABC-619): Expose existing methods in the doc, and add getSelection()

---

src/modules/base/relationshipGraph/__tests__/relationshipGraph.test.js
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

This is a fix for the deployment on Salesforce. It should not be part of the release notes.

[fix] (ABC-630): Normalize relationship graph query selectors

---

src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.html
src/modules/base/primitiveRelationshipGraphGroup/primitiveRelationshipGraphGroup.js
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.html
src/modules/base/primitiveRelationshipGraphLevel/primitiveRelationshipGraphLevel.js
src/modules/base/relationshipGraph/__tests__/relationshipGraph.test.js
src/modules/base/relationshipGraph/relationshipGraph.html
src/modules/base/relationshipGraph/relationshipGraph.js

This is a fix for the deployment on Salesforce. It should not be part of the release notes.

[fix] (ABC-630): Normalize relationship graph primitives query selectors

---

src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/tree/__tests__/tree.test.js
src/modules/base/tree/tree.js

**Tree**
- Added `previousLevelPath` to the `change` event, to identify the previous position of the item when the action is `move`.
**Tree**
- Fixed the indentation removal when an item was sorted.

[feat] (ABC-643): Add previousLevelPath to tree change event

---

src/modules/base/primitiveTreeItem/__tests__/primitiveTreeItem.test.js
src/modules/base/primitiveTreeItem/primitiveTreeItem.html
src/modules/base/primitiveTreeItem/primitiveTreeItem.js

**Tree**
- Fixed the inline editing: the last character entered is now saved when clicking on the check button.

[fix] (ABC-648): Fix tree inline editing not saving last character

---

src/modules/base/primitiveTreeItem/primitiveTreeItem.js
src/modules/base/tree/tree.js

**Tree**
- Fixed selection not being erased when an empty value was passed to `selected-items`.

[fix] (ABC-711): Allow unselection of selected items in tree

---

src/modules/base/pageHeader/pageHeader.css
src/modules/base/pageHeader/pageHeader.html

**Page header**
- Removed the duplicated `actions` slot that was causing problems when the slot contained conditional declarations.

[fix] (ABC-710): Remove duplicate actions slot in page header

---

src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/avatarGroup/__docs__/avatarGroup.jsdoc.js
src/modules/base/avatarGroup/avatarGroup.css
src/modules/base/colorPicker/__docs__/colorPicker.jsdoc.js
src/modules/base/colorPicker/colorPicker.css
src/modules/base/colorPicker/colorPicker.js
src/modules/base/combobox/combobox.css
src/modules/base/dateTimePicker/__docs__/dateTimePicker.jsdoc.js
src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/iconPicker/__docs__/iconPicker.jsdoc.js
src/modules/base/iconPicker/iconPicker.css
src/modules/base/iconPicker/iconPicker.js
src/modules/base/illustration/__docs__/illustration.jsdoc.js
src/modules/base/illustration/illustration.css
src/modules/base/primitiveTreeItem/primitiveTreeItem.css
src/modules/base/tree/__docs__/tree.jsdoc.js
src/modules/base/tree/tree.css

- Added new styling hook for border
--avonni-avatar-group-avatar-stack-styling-border
- Added new styling hooks for label
--avonni-color-picker-label-text-color
--avonni-color-picker-label-font-size
--avonni-color-picker-label-font-style
--avonni-color-picker-label-font-weight
**DatetimePicker**
- Added new styling hooks for label
--avonni-date-time-picker-label-text-color
--avonni-date-time-picker-label-font-size
--avonni-date-time-picker-label-font-weight
--avonni-date-time-picker-label-font-style
**iconPicker**
- Added new styling hooks for label
--avonni-icon-picker-label-text-color
--avonni-icon-picker-label-font-size
--avonni-icon-picker-label-font-weight
--avonni-icon-picker-label-font-style
**illustration**
- Added new styling hooks for title …

[Feat](ABC-715): Adding and Changing Styling hooks

---

src/modules/base/metric/__docs__/metric.jsdoc.js
src/modules/base/metric/metric.css
src/modules/base/primitiveMetric/primitiveMetric.css

**Metric**
- Added font style styling hooks :
--avonni-metric-description-font-style
--avonni-metric-label-font-style
--avonni-metric-prefix-font-style
--avonni-metric-secondary-prefix-font-style
--avonni-metric-secondary-suffix-font-size
--avonni-metric-secondary-value-font-style
--avonni-metric-suffix-font-style
--avonni-metric-value-font-style

[feat](ABC-721): Metric - Added font style styling hooks

---

src/modules/base/metric/__docs__/metric.stories.js
src/modules/base/metric/__tests__/metric.test.js
src/modules/base/metric/metric.js
src/modules/base/primitiveMetric/__tests__/primitiveMetric.test.js
src/modules/base/primitiveMetric/primitiveMetric.html
src/modules/base/primitiveMetric/primitiveMetric.js

**Metric**
- Removed the default value of 0 for the `value` attribute. The `value` attribute is not required anymore.
- A `null` value passed to `value` or `secondary-value` will not be normalized to 0 anymore.

[defaults] (ABC-724): Remove default value in metric

---

src/modules/base/calendar/calendar.js

**Calendar**
- Fixed error when an invalid date was passed to `min` or `max`. The default `min` and `max` values will be used instead.

[fix] (ABC-716): Use default values for invalid min and max

---

src/modules/base/calendar/calendar.css

**Calendar**
- Fixed the interval display when the component is used on the Salesforce platform.

[fix] (ABC-728): Fix calendar interval display in Salesforce

---

src/modules/base/calendar/__docs__/calendar.stories.js
src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.html
src/modules/base/calendar/calendar.js
src/modules/base/calendar/date.js
src/modules/base/calendar/dateLabel.js
src/modules/base/utilsPrivate/dateTimeUtils.js
src/modules/base/utilsPrivate/utilsPrivate.js

**Calendar**
- Implemented support of string dates in `date-labels`
- Blocked the number of markers displayed on a single date to a maximum of three.

[fix][refactor] (ABC-732): Refactor and support string dates in calendar

---

src/modules/base/inputDateRange/__tests__/inputDateRange.test.js
src/modules/base/inputDateRange/inputDateRange.js

- Updated the `change` event to return valid ISO8601 strings as `startDate` or `endDate` values.
- Prevented the `change` event keys from containing time strings with no date.

[fix] (ABC-734): Return ISO8601 strings in input date range change event

---

src/modules/base/inputDateRange/inputDateRange.html
src/modules/base/inputDateRange/inputDateRange.js

- Prevented `null` from being used as a valid date in `start-date` and `end-date`.
- Added the possibility to clear the date inputs with the keyboard.

[fix] (ABC-750): Improvements to input date range

---

src/modules/base/carousel/carousel.css

**Carousel**
- Fix issues with indicators styling hooks

[Fix](ABC-718): Carousel - Styling hook for active indicator not working

---

src/modules/base/carousel/__docs__/carousel.stories.js
src/modules/base/carousel/__tests__/carousel.test.js
src/modules/base/carousel/carousel.js

**Carousel**
- current-panel is chosen by name of item instead of index

[feat](ABC-793): Carousel - currentPanel is chosen by name instead of index

---

src/modules/base/inputDateRange/inputDateRange.js

- Fixed selected time zone not being properly added to the dates when the user's locale is not English.

[fix] (ABC-798): Ignore locale when adding time zone in input date range

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/__docs__/data.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/primitiveActivityTimelineItem/__tests__/primitiveActivityTimelineItem.test.js
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js

- Added a `checked` key to the items, to allow for pre-checked items.

[fix] (ABC-800): Add checked key to activity timeline items

---

src/modules/base/inputCounter/inputCounter.js

**Input Counter**
- Prevented the normalization of a `null` `min` or `max` into a 0.

[defaults][fix] (ABC-806): Handle null min and max in input counter

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

Make sure keyboard events are sent event if there is more than one column and list is not sortable.
Make overflow visible on single-line.
Delete repeating lines.

[fix] (abc-539): Check if list can be sorted

---

src/modules/base/colorPalette/colorPalette.js
src/modules/base/colorPalette/grid.html
src/modules/base/colorPalette/list.html
src/modules/base/colorPicker/__tests__/colorPicker.test.js
src/modules/base/colorPicker/colorPicker.html
src/modules/base/colorPicker/colorPicker.js

**Color picker**
- Added a loading spinner if the color palette is loading when the dropdown is opened.
**Color palette**
- Improved performance on first load.

[fix] (ABC-816): Speed up the color palette in salesforce

---

src/modules/base/combobox/__docs__/combobox.jsdoc.js
src/modules/base/combobox/combobox.css
src/modules/base/combobox/combobox.js
src/modules/base/primitiveCombobox/primitiveCombobox.css

**Combobox**
- Merged border and border-radius styling hooks into two shorthands.
- Removed: `--avonni-combobox-input-radius-border-bottom-left`, `--avonni-combobox-input-radius-border-bottom-right`, `--avonni-combobox-input-radius-border-top-left`, `--avonni-combobox-input-radius-border-top-right``--avonni-combobox-input-sizing-border-bottom`, `--avonni-combobox-input-sizing-border-top`, `--avonni-combobox-input-sizing-border-left` and `--avonni-combobox-input-sizing-border-right`.
- Added: `--avonni-combobox-input-radius-border` and `--avonni-combobox-input-sizing-border`.

[feat] (ABC-821): Update combobox styling hooks to follow convention

---

src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js

- Fixed error on action click, when the component is implemented in a Salesforce platform where Lightning Locker is enabled.

[fix] (ABC-822): Remove event.target in pill container

---

src/modules/base/colorPicker/colorPicker.html
src/modules/base/iconPicker/__docs__/iconPicker.stories.js
src/modules/base/iconPicker/__examples__/iconPicker.js
src/modules/base/iconPicker/__tests__/iconPicker.test.js
src/modules/base/iconPicker/iconPicker.css
src/modules/base/iconPicker/iconPicker.html
src/modules/base/iconPicker/iconPicker.js

- Added `hide-clear-icon` attribute.
- Removed fixed width of 17rem. The icon picker width will now adapt to its parent.

[feat] (ABC-823): Add hide clear icon to icon picker and remove fixed width

---

src/modules/base/inputToggle/inputToggle.js

**Input Toggle**
- Prevented an error when implemented in Salesforce with Locker enabled.

[fix] (ABC-815): Do not use ContentMutation util in input toggle

---

src/modules/base/avatar/__docs__/avatar.jsdoc.js
src/modules/base/primitiveAvatar/primitiveAvatar.css
src/modules/base/primitiveAvatar/primitiveAvatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.js

** Avatar + Avatar group
- Fixed the size of the fallback icon for x-large and xx-large sizes.
- Fixed the `--avonni-avatar-radius-border` styling hook.
Correction to doc, --avonni-avatar-status-unknown-color-background had a typo.

[fix] (abc-762): Fix avatar icon size and border radius hook

---

src/modules/base/iconPicker/iconPicker.html
src/modules/base/iconPicker/iconPicker.js
src/modules/base/tabBar/__tests__/tabBar.test.js
src/modules/base/tabBar/tabBar.js

**Tab Bar**
- Added `focus()` method.
- Prevented the popover from closing on click on a category tab.

[fix] (ABC-856): Fix popover closing on tab click in icon picker

---

src/modules/base/list/__tests__/list.test.js
src/modules/base/list/list.html
src/modules/base/list/list.js

**List**
- Prevented the `itemclick` event from being fired when the Enter or Space keys are pressed on an action.

[fix] (ABC-863): Prevent itemclick on keyboard actionclick in list

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.html
src/modules/base/slider/slider.js

**Slider**
- Prevented the update of the given value, when it is outside of the min/max range.
- Fixed the update of the track display when updating the min/max after the first render.
- Fixed the update of the slider height, when the slider is vertical and the parent height is set after the slider render.

[fix] (ABC-871): Fix property updates after first render

---

src/modules/base/pillContainer/__tests__/pillContainer.test.js
src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.html
src/modules/base/pillContainer/pillContainer.js

- Fixed the position of the actions dropdown, when the pill container is inside a parent with a `transform` CSS property.

[fix] (ABC-886): Fix pill container actions popover position

---

src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.js

- Removed the `single-line` border when no items are set.

[fix] (ABC-884): Remove the single-line border for empty pill container

---

src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.js

- Added the `goToDate()` method.
- Updated the component so it is automatically centered on the right date when loaded, depending on the current date, the `value`, the `min` and the `max`.

[feat] (ABC-895): Add goToDate() and auto center to date time picker

---

src/modules/base/calendar/calendar.css
src/modules/base/calendar/calendar.js

**Calendar**
- Fixed interval background not appearing when the component does not have a parent with a `z-index` CSS property.

[fix] (ABC-912): Fix invisible calendar interval background

---

jest-mock/components/base/combobox/combobox.html
jest-mock/components/base/combobox/combobox.js
jest.config.js
src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.css
src/modules/base/calendar/calendar.html
src/modules/base/combobox/__tests__/combobox.test.js

**Calendar**
- Replaced the Lightning Combobox used for the year dropdown by an Avonni Combobox. Prevented the dropdown from not closing when used inside a popover.

[fix] (ABC-911): Use avonni combobox for calendar years

---

src/modules/base/inputDateRange/__tests__/inputDateRange.test.js
src/modules/base/inputDateRange/inputDateRange.js

- Prevent the time zone being from being erased when passed from the filter menu, to the input date range, to the dropdown calendars.

[fix] (ABC-906): Fix input date range timezone when used in filter menu

---

src/modules/base/inputChoiceSet/__tests__/inputChoiceSet.test.js
src/modules/base/inputChoiceSet/inputChoiceSet.css
src/modules/base/inputChoiceSet/inputChoiceSet.js

- On hover, displayed a pointer cursor on the whole button, instead of displaying it only on the label.

[feat] (ABC-915): Show a pointer on any part of the choice set options

---

src/modules/base/visualPickerLink/__docs__/visualPickerLink.jsdoc.js
src/modules/base/visualPickerLink/__docs__/visualPickerLink.stories.js
src/modules/base/visualPickerLink/__tests__/visualPickerLink.test.js
src/modules/base/visualPickerLink/shared.css
src/modules/base/visualPickerLink/visualPickerLink.html
src/modules/base/visualPickerLink/visualPickerLink.js
src/modules/base/visualPickerLink/visualPickerLinkInfoOnly.html

- Added new styling hooks
```
--avonni-visual-picker-link-tile-color-background
--avonni-visual-picker-link-tile-color-background-info-only
--avonni-visual-picker-link-tile-radius-border
--avonni-visual-picker-link-tile-sizing-border
--avonni-visual-picker-link-tile-styling-border
--avonni-visual-picker-link-tile-color-border
--avonni-visual-picker-link-tile-sizing-border-hover
--avonni-visual-picker-link-tile-styling-border-hover
--avonni-visual-picker-link-tile-color-border-hover
--avonni-visual-picker-link-title-text-color
--avonni-visual-picker-link-title-font-size
--avonni-visual-picker-link-title-font-style
--avonni-visual-picker-link-title-font-weight
```
- Fixed issue with checkmark when completed and no icon

[Fix](ABC-916): Visual picker link - Hide checkmark when no icon

---

src/modules/base/primitiveSchedulerCalendar/__tests__/primitiveSchedulerCalendar.test.js
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.html
src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js
src/modules/base/schedulerUtils/cell.js
src/modules/base/schedulerUtils/cellGroup.js

**Scheduler**
- Fixed event creation on a Sunday, in the calendar display with one-day time span.
- Handled the spring time change in the calendar display. The skipped hour that does not exist is shown, but styled differently than the others.

[fix] (ABC-922): Handle non existent hour on time change in scheduler

---

src/modules/base/slider/__tests__/slider.test.js
src/modules/base/slider/slider.js

**Slider**
- Prevented performance issue when the ticks are visible and the step is very small. The maximum number of visible ticks has been set to 500.

[fix] (ABC-928): Display a maximum of 500 ticks on the slider

---

src/modules/base/carousel/carousel.js

**Carousel**
- Fixed super fast scrolling when `scroll-duration` was set to `null`.

[fix] (ABC-941): Fix carousel super fast scroll duration

---

src/modules/base/pillContainer/pillContainer.css
src/modules/base/pillContainer/pillContainer.js

- Prevented a screen freeze, when a single-line pill container was expanded, but the first pill could not fit the available width.

[fix] (ABC-958): Prevent single line pill container infinite loop on expand

---

src/modules/base/kanban/kanban.js

**Kanban**
- Add missing parameter in `ResizeObserver`
- Fix crash issues caused by `scrollBy()` and `DOMMatrixReadOnly`

[fix] (ABC-980): Kanban - Fix issue with ResizeObserver

---

src/modules/base/kanban/__docs__/kanban.stories.js
src/modules/base/kanban/__tests__/kanban.test.js
src/modules/base/kanban/group.js
src/modules/base/kanban/groupBuilder.js
src/modules/base/kanban/kanban.js
src/modules/base/kanban/shared.css

**Kanban**
- Fix field not found for `summarize-field-name` property
- Fix component render issue after value change for `sub-group-field-name` and `summarize-field-name` 
- Fix summary update
- Fix cursor style for disabled columns

[fix] (ABC-988): Kanban - Group summarization not updating

---

src/modules/base/datatable/datatable.js

**Data Table**
- Badge name is not truncate if text is big

[Fix](ABC-996): Data Table - badge name is not truncate if text is big

---

src/modules/base/primitiveDatatableIeditPanelCustom/primitiveDatatableIeditPanelCustom.js

**Data table**
- Rich-text disappear when editing font size or family

[Fix](ABC-997) Data Table: Rich-text disappear when editing font size or family

---

src/modules/base/buttonIconPopover/__tests__/buttonIconPopover.test.js
src/modules/base/buttonIconPopover/buttonIconPopover.html
src/modules/base/buttonIconPopover/buttonIconPopover.js

**Button Icon Popover**
- Added the `open` event.
- Prevented dispatch of the `close` event when the `close()` method is called programatically.

[feat] (ABC-1003): Add open event to button icon popover

---

src/modules/base/filterMenu/filterMenuVertical.html

- Fixed the display of a loading spinner for vertical `range` and `date-range` filter menus, when `is-loading` is true.

[fix] (ABC-1025): Show loading spinner for vertical range filter menus

---

src/modules/base/primitiveSchedulerHeaderGroup/primitiveSchedulerHeaderGroup.js
src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js

**Scheduler**
- Fixed error thrown when the scheduler properties are updated before its header had time to load.

[fix] (ABC-1036): Fix scheduler error when headers have not loaded

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevented the combobox from displaying the old value, when the new value passed is `null`.

[fix] (ABC-1045): Clear combobox displayed value when new value is null

---

src/modules/base/pagination/pagination.js

**Pagination**
- Normalized the values passed to `ellipsis-text`, `per-page` and `total-rows`, to make sure their type is valid. If the type is invalid, use the default value instead.

[defaults][fix] (ABC-1037): Normalize pagination default values

---

src/modules/base/primitiveCellCombobox/primitiveCellCombobox.js

**Data Table**
- Fixed error when no options were passed to a combobox cell.

[defaults][fix] (ABC-1055): Normalize data table prim cell combobox opts

---

.storybook/manager.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevented some options from being hidden when the combobox is at the bottom of the window. The dropdown height is automatically reduced to prevent overflowing the window, to a minimum of 60 pixels.

[feat] (ABC-1056): Prevent combobox dropdown from overflowing the window

---

src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceAgenda.test.js
src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceCalendar.test.js
src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceTimeline.test.js
src/modules/base/primitiveSchedulerEventOccurrence/eventOccurrence.css
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js

**Scheduler**
- Fixed the display of events when they have no title.

[fix] (ABC-1079): Show scheduler events with empty titles

---

src/modules/base/datatable/datatable.js

**Data Table**
- Fixed the update of the row selection button type (radio or checkbox), when the value of `max-row-selection` is going from `1` to `undefined`.

[fix] (ABC-1084): Patch lwc datatable row select button type update

---

src/modules/base/inputDateRange/inputDateRange.js

- Prevented the dispatch of a `change` event containing the same values as the current ones.

[fix] (ABC-1089): Prevent error and useless change event in date range

---

src/modules/base/filterMenu/__tests__/filterMenu.test.js
src/modules/base/filterMenu/filterMenu.js
src/modules/base/filterMenu/filterMenuVertical.html
src/modules/base/filterMenuGroup/filterMenuGroup.js

- Added support of `open` and `close` events in the vertical variant, if the menu is collapsible. The events will be fired when the collapsible section is opened or closed.

[feat] (ABC-1090): Fire open and close events in vertical filter menu

---

src/modules/base/dateTimePicker/__docs__/dateTimePicker.stories.js
src/modules/base/dateTimePicker/__examples__/weekly/weekly.html
src/modules/base/dateTimePicker/__examples__/weekly/weekly.js
src/modules/base/dateTimePicker/__tests__/dateTimePicker.test.js
src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/dateTimePicker/dateTimePicker.js
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/dateComputations.js
src/modules/base/schedulerUtils/schedulerUtils.js
src/modules/base/utilsPrivate/dateTimeUtils.js
src/modules/base/utilsPrivate/utilsPrivate.js

- Loosened the `disabled-date-times` attribute, so the dates it contains does not need to be the exact time of a slot. For example, if `2023-10-16T10:03` is included in the array, a time slot starting at 10:00 would be disabled.

[fix] (ABC-1077): Disable date time picker slot if the given date is included in the slot

---

src/modules/base/primitiveSchedulerCalendar/primitiveSchedulerCalendar.js

**Scheduler**
- Removed the loading spinner that was not disappearing when the available time frames or months were updated, in the calendar display.

[fix] (ABC-1098): Fix loading on scheduler available times update

---

src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/scheduler.html
src/modules/base/scheduler/scheduler.js

**Scheduler**
- Added a fixed format for all day events dates, in the event details popover. If the `from` or the `to` keys are present in the event display fields, and the selected event is "all day", the from and to dates will be displayed in the format "Nov. 14, 2023", without the time. If the event only spans on one day, only the from date will be displayed.

[feat] (ABC-1102): Improve date format of all day events in scheduler

---

src/modules/base/primitiveSchedulerAgenda/primitiveSchedulerAgenda.js
src/modules/base/primitiveSchedulerCalendar/__tests__/primitiveSchedulerCalendar.test.js
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js
src/modules/base/primitiveSchedulerTimeline/__tests__/primitiveSchedulerTimeline.test.js
src/modules/base/scheduler/__docs__/data.js
src/modules/base/scheduler/__docs__/scheduler.jsdoc.js
src/modules/base/scheduler/__examples__/agenda/agenda.js
src/modules/base/scheduler/__examples__/availableAndDisabledTimes/availableAndDisabledTimes.js
src/modules/base/scheduler/__examples__/calendar/calendar.js
src/modules/base/scheduler/__examples__/labels/labels.js
src/modules/base/scheduler/__examples__/readOnly/readOnly.js
src/modules/base/scheduler/__examples__/verticalTimeline/verticalTimeline.js
src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/scheduler/scheduler.js
src/modules/base/schedulerUtils/dateComputations.js
src/modules/base/schedulerUtils/event.js

**Scheduler**
- Added a `dateFormat` key to the events.
- Updated the display of the events that only have a `from` date. Their end date is now the same as their starting date.

[feat] (ABC-1104): Improve support of scheduler event dates

---

src/modules/base/visualPicker/visualPicker.css
src/modules/base/visualPicker/visualPicker.html
src/modules/base/visualPicker/visualPicker.js

- Fixed an issue with fields not being displayed properly if the size is responsive
- Removed overlay background if the content of the item is empty

[feat] (ABC-1101):  Visual Picker - If no title, description and tags, remove the overlay background

---

src/modules/base/scheduler/__tests__/scheduler.test.js
src/modules/base/utilsPrivate/dateTimeUtils.js

**Scheduler**
- Broadened the accepted formats for available time frames, to accept times including milliseconds.

[fix] (ABC-1109): Allow milliseconds in scheduler time frames

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Fixed the search to allow for the space character.

[fix] (ABC-1111): Allow space character in combobox search

---

src/modules/base/visualPicker/visualPicker.js

- If present and no figure title is specified, the figure image will still be displayed

[feat] (ABC-1121): Visual Picker - If no Figure title specified, the image should still be displayed

---

src/modules/base/primitiveSchedulerHeaderGroup/schedulerHeader.js

**Scheduler**
- Fixed the wrong week number displayed at the beginning of the month, in the timeline display header.

[fix] (ABC-1138): Fix week number in scheduler timeline headers

---

src/modules/base/primitiveSchedulerTimeline/primitiveSchedulerTimeline.js

**Scheduler**
- Prevented the timeline display from loading indefinitely when a time span identical to the current one is passed to the scheduler.

[fix] (ABC-1144): Prevent scheduler loading for identical new time span

---

src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js

**Scheduler**
- Fixed the span of multi-day events, in the monthly calendar display. When the events had the key `allDay`, they were only spanning on one cell.

[fix] (ABC-1145): Fix scheduler calendar multi day events display

---

src/modules/base/activityTimeline/__docs__/activityTimeline.jsdoc.js
src/modules/base/activityTimeline/__docs__/activityTimeline.stories.js
src/modules/base/activityTimeline/__tests__/activityTimeline.test.js
src/modules/base/activityTimeline/__tests__/horizontalActivityTimeline.test.js
src/modules/base/activityTimeline/activityTimeline.js
src/modules/base/activityTimeline/horizontalActivityTimeline.js
src/modules/base/activityTimeline/verticalActivityTimeline.html
src/modules/base/primitiveActivityTimelineItem/primitiveActivityTimelineItem.js
src/modules/base/utilsPrivate/dateTimeUtils.js
src/modules/base/utilsPrivate/utilsPrivate.js

- Refactor of `itemDateFormat` attribute. In addition to a custom format string, you can now set it to 'STANDARD', 'RELATIVE' or use one of [luxon's format preset names](https://moment.github.io/luxon/#/formatting?id=presets)

[Feat](ABC-1139): Activity Timeline - Improve item date format attribute

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevented the erasion of the current search value, when an option is selected and new options are passed to the combobox.

[fix] (ABC-1153): Fix combobox search erasion when an option is selected

---

src/modules/base/expandableSection/expandableSection.css
src/modules/base/expandableSection/expandableSection.html

- Use `display:none` on the closed section content to fix white space problem.

[fix](ABC-1174): Fix expandable section content taking up white space when closed

---

src/modules/base/scheduler/scheduler.html

**Scheduler**
- Prevented height change when `is-loading` is updated. The loading spinner will now be displayed on top of the scheduler, instead of replacing it.

[feat] (ABC-1180): Show loading spinner on top of scheduler

---

jest-mock/components/base/layoutItem/layoutItem.js
src/modules/base/dateTimePicker/dateTimePicker.css
src/modules/base/dateTimePicker/dateTimePicker.html
src/modules/base/layout/__docs__/layout.stories.js
src/modules/base/layout/__examples__/layout.js
src/modules/base/layoutItem/__tests__/layoutItem.test.js
src/modules/base/layoutItem/layoutItem.css
src/modules/base/layoutItem/layoutItem.js
src/modules/base/storybookWrappers/layout/layout.html
src/modules/base/storybookWrappers/layout/layout.js

> Remove any mention to `--avonni-layout-item-layout-flex-grow` and `--avonni-layout-item-layout-flex-shrink` from the release notes.
**Layout Item**
- Added `grow` and `shrink` attributes.

[feat] (ABC-1181): Replace layout styling hooks by grow and shrink properties

---

src/modules/base/primitiveSchedulerEventOccurrence/__tests__/primitiveSchedulerEventOccurrenceBase.test.js
src/modules/base/primitiveSchedulerEventOccurrence/primitiveSchedulerEventOccurrence.js

**Scheduler**
- Updated the events background transparency, so it is set to transparent only when the end date is passed, instead of the start date.

[fix] (ABC-1204): Use event end date to set scheduler event colour

---

src/modules/base/activityTimeline/activityTimeline.js

- Set enough space for spinner to show properly when component is loading with no items.

[fix](ABC-1219): Fix spinner not showing properly when isLoading with no items

---

src/modules/base/card/card.js

**Card**
- Updated the card so the header is visible when only the actions slot is filled.

[fix] (ABC-1230): Show card header if only the actions slot is filled

---

src/modules/base/card/card.css

**Card**
- Fixed nested cards spacing from being affected by their parent, when nested inside another card.

[fix] (ABC-1237): Prevent nested card from being styled by their parent

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Prevents the dropdown menu from closing if `isMultiSelect` is set to true.

[Feat](ABC-1244): Combobox - Prevents the dropdown menu from closing if isMultiSelect is true

---

src/modules/base/calendar/calendar.js

**Calendar**
- Allowed navigation to the next month when only part of its dates are disabled.

[fix] (ABC-1250): Allow nav if only part of next month is disabled

---

src/modules/base/calendar/__tests__/calendar.test.js
src/modules/base/calendar/calendar.js

**Calendar**
- Prevented focus on previous month's date, when the current month's focused date has the same number (for example focusing the 28th of June when the date that should be focused is the 28th of July).

[fix] (ABC-1251): Prevent focus on previous calendar month's date

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1262): Prevent error when combobox option value is empty

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1305): Reset combobox option position on level change

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1309): Prevent update of combobox opt without passing by set

---

src/modules/base/verticalVisualPicker/__docs__/verticalVisualPicker.jsdoc.js
src/modules/base/verticalVisualPicker/verticalVisualPicker.css
src/modules/base/visualPicker/__docs__/visualPicker.jsdoc.js
src/modules/base/visualPicker/visualPicker.css

- Fallback value for `--avonni-visual-picker-header-font-weight` is now 400 instead of 700.
- Fallback value for `--avonni-vertical-visual-picker-header-font-weight` is now 400 instead of 700.

[feat](ABC-1320): Remove the bold label for Visual Picker and Vertical Visual Picker

---

src/modules/base/avatarGroup/avatarGroup.html
src/modules/base/avatarGroup/avatarGroup.js

- Fixed issue with the "show more" popover not displaying correctly.

[fix](ABC-1324): Avatar Group - Issue "Show More" button with empty list of hidden items

---

src/modules/base/buttonMenu/buttonMenu.css

- Fixed issue with dropdown width when it contained lightning items with icons. The issue was present in the Salesforce platform starting with the Spring'25 release.

[fix] (ABC-1330): Fix button menu width when items have an icon

---

src/modules/base/tooltipLibrary/tooltipLibrary.js

[fix] (ABC-1337): Avoid error if tooltip is destroyed before init

---

src/modules/base/pagination/pagination.js

**Pagination**
- Fixed error when `null` was passed as the value of `total-rows` or `per-page`. The value is now normalized to the default value of these attributes.

[fix] (ABC-1332): Normalize null passed to pagination number properties

---

src/modules/base/combobox/__docs__/combobox.stories.js
src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Removed invalid error after item deselect for `required` and non multi-select input.

[Fix](ABC-1350): Combobox - Remove invalid input error after item deselect

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

[fix] (ABC-1369): Prevent combobox infinite loop after loadmore event

---

src/modules/base/filterMenu/nestedItemsUtils.js

[fix] (ABC-1386): Fix select all nested children in filter menu

---

src/modules/base/primitiveCombobox/primitiveCombobox.js

**Combobox**
- Respect group order of definition

[fix](ABC-1393): Primitive Combobox - Respect group order of definition

---

src/modules/base/avatar/__docs__/avatar.jsdoc.js
src/modules/base/primitiveAvatar/primitiveAvatar.css
src/modules/base/primitiveAvatar/primitiveAvatar.html
src/modules/base/primitiveAvatar/primitiveAvatar.js

**Avatar**
- Added styling hooks for the `entity`.
- `--avonni-avatar-entity-border-radius`
- `--avonni-avatar-entity-border-color`
- `--avonni-avatar-entity-border-style`
- `--avonni-avatar-entity-border-size`
- `--avonni-avatar-entity-background-color`
- `--avonni-avatar-entity-foreground-color`
- `--avonni-avatar-entity-foreground-color-utility`
- `--avonni-avatar-entity-image-object-fit`
**Avatar**
- Fixed the `entity` variant not changing the `border-radius` of the `entity`
- Disabled simultaneous display of an `image` and `initials` within the `entity`.

[feat] (ABC-1455): Avatar - Entity styling hooks
